//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFSistemas.VLI.ACTWeb.Web.Consulta {
    
    
    public partial class ConsultaVMA {
        
        /// <summary>
        /// Label2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label2;
        
        /// <summary>
        /// lblUsuarioMatricula control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblUsuarioMatricula;
        
        /// <summary>
        /// lblUsuarioLogado control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblUsuarioLogado;
        
        /// <summary>
        /// lblUsuarioPerfil control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblUsuarioPerfil;
        
        /// <summary>
        /// lblUsuarioMaleta control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblUsuarioMaleta;
        
        /// <summary>
        /// ddlFiltroSB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlFiltroSB;
        
        /// <summary>
        /// lnkPesquisar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lnkPesquisar;
        
        /// <summary>
        /// lnkLImpar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lnkLImpar;
        
        /// <summary>
        /// semPontodeTroca control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl semPontodeTroca;
        
        /// <summary>
        /// lblNomeSbSemPontoTroca control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblNomeSbSemPontoTroca;
        
        /// <summary>
        /// lblVelocidade_VMA_SemPontoTroca_L1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblVelocidade_VMA_SemPontoTroca_L1;
        
        /// <summary>
        /// lblSentido_VMA_SemPontoTroca_L1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSentido_VMA_SemPontoTroca_L1;
        
        /// <summary>
        /// lblKmInicialFinal_SemPontoTroca_L1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblKmInicialFinal_SemPontoTroca_L1;
        
        /// <summary>
        /// lblInicioFim_VMA_SemPontoTroca_L1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblInicioFim_VMA_SemPontoTroca_L1;
        
        /// <summary>
        /// lblLatitude_VMA_SemPontoTroca_L1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblLatitude_VMA_SemPontoTroca_L1;
        
        /// <summary>
        /// lblLongitude_VMA_SemPontoTroca_L1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblLongitude_VMA_SemPontoTroca_L1;
        
        /// <summary>
        /// lblTamanhoPatio_VMA_SemPontoTroca_L1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTamanhoPatio_VMA_SemPontoTroca_L1;
        
        /// <summary>
        /// lblVelocidade_VMA_SemPontoTroca_L2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblVelocidade_VMA_SemPontoTroca_L2;
        
        /// <summary>
        /// lblSentido_VMA_SemPontoTroca_L2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSentido_VMA_SemPontoTroca_L2;
        
        /// <summary>
        /// lblKmInicialFinal_SemPontoTroca_L2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblKmInicialFinal_SemPontoTroca_L2;
        
        /// <summary>
        /// lblInicioFim_VMA_SemPontoTroca_L2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblInicioFim_VMA_SemPontoTroca_L2;
        
        /// <summary>
        /// lblLatitude_VMA_SemPontoTroca_L2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblLatitude_VMA_SemPontoTroca_L2;
        
        /// <summary>
        /// lblLongitude_VMA_SemPontoTroca_L2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblLongitude_VMA_SemPontoTroca_L2;
        
        /// <summary>
        /// lblTamanhoPatio_VMA_SemPontoTroca_L2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTamanhoPatio_VMA_SemPontoTroca_L2;
        
        /// <summary>
        /// lblReducao_VMA_SemPontoTroca control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblReducao_VMA_SemPontoTroca;
        
        /// <summary>
        /// comPontodeTroca control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl comPontodeTroca;
        
        /// <summary>
        /// lblNomeSbComPontoTroca control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblNomeSbComPontoTroca;
        
        /// <summary>
        /// lblVelocidade_VMA_ComPontoTroca_L1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblVelocidade_VMA_ComPontoTroca_L1;
        
        /// <summary>
        /// lblSentido_VMA_ComPontoTroca_L1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSentido_VMA_ComPontoTroca_L1;
        
        /// <summary>
        /// lblKmInicialFinal_ComPontoTroca_L1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblKmInicialFinal_ComPontoTroca_L1;
        
        /// <summary>
        /// lblInicioFim_VMA_ComPontoTroca_L1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblInicioFim_VMA_ComPontoTroca_L1;
        
        /// <summary>
        /// lblLatitude_VMA_ComPontoTroca_L1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblLatitude_VMA_ComPontoTroca_L1;
        
        /// <summary>
        /// lblLongitude_VMA_ComPontoTroca_L1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblLongitude_VMA_ComPontoTroca_L1;
        
        /// <summary>
        /// lblTamanhoPatio_VMA_ComPontoTroca_L1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTamanhoPatio_VMA_ComPontoTroca_L1;
        
        /// <summary>
        /// lblVelocidade_VMA_ComPontoTroca_L2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblVelocidade_VMA_ComPontoTroca_L2;
        
        /// <summary>
        /// lblSentido_VMA_ComPontoTroca_L2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSentido_VMA_ComPontoTroca_L2;
        
        /// <summary>
        /// lblKmInicialFinal_ComPontoTroca_L2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblKmInicialFinal_ComPontoTroca_L2;
        
        /// <summary>
        /// lblInicioFim_VMA_ComPontoTroca_L2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblInicioFim_VMA_ComPontoTroca_L2;
        
        /// <summary>
        /// lblLatitude_VMA_ComPontoTroca_L2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblLatitude_VMA_ComPontoTroca_L2;
        
        /// <summary>
        /// lblLongitude_VMA_ComPontoTroca_L2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblLongitude_VMA_ComPontoTroca_L2;
        
        /// <summary>
        /// lblTamanhoPatio_VMA_ComPontoTroca_L2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTamanhoPatio_VMA_ComPontoTroca_L2;
        
        /// <summary>
        /// lblReducao_VMA_ComPontoTroca control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblReducao_VMA_ComPontoTroca;
        
        /// <summary>
        /// lblPontosDeTrocaNomeSB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblPontosDeTrocaNomeSB;
        
        /// <summary>
        /// lblVelocidade_PT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblVelocidade_PT;
        
        /// <summary>
        /// lblUltimaLicenca_PT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblUltimaLicenca_PT;
        
        /// <summary>
        /// lblKm_Troca_PT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblKm_Troca_PT;
        
        /// <summary>
        /// lblLatitude_PT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblLatitude_PT;
        
        /// <summary>
        /// lblLongitude_PT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblLongitude_PT;
    }
}
