--------------------------------------------------------------------------------------------------------
-- SISTEMA    	: ACTWEB - Sistema de Controle e Automação de Trens
-- TABELA       : TT_SUBROTA_AOP 
-- SEQUENCE    	: TT_SUBROTA_AOP_SEQUENCE
-- CRIADO    EM	: 04/10/2016
-- ANALISTA    	: DENER VIANA
-- AÇÃO			: Adicionando campo na tabela
--------------------------------------------------------------------------------------------------------

--DESFAZER
--ALTER TABLE TT_SUBROTA_AOP DROP COLUMN(TTS_PNT_SUB);

-- FAZER
ALTER TABLE ACTPP.TT_SUBROTA_AOP ADD (TTS_PNT_SUB		VARCHAR2(1 BYTE)	DEFAULT 'N'	NOT NULL);

-- SUBROTA: 1 - EYD-EEL 
UPDATE ACTPP.TT_SUBROTA_AOP SET TTS_PNT_SUB = 'S' WHERE ACTPP.TT_SUBROTA_AOP.TTS_ID_AOP IN (1, 2, 161, 162, 966, 967);

-- SUBROTA: 2 - EYD-EIA
UPDATE ACTPP.TT_SUBROTA_AOP SET TTS_PNT_SUB = 'S' WHERE ACTPP.TT_SUBROTA_AOP.TTS_ID_AOP IN (163, 164, 197, 198);

-- SUBROTA: 3 - EIA-EGS
UPDATE ACTPP.TT_SUBROTA_AOP SET TTS_PNT_SUB = 'S' WHERE ACTPP.TT_SUBROTA_AOP.TTS_ID_AOP IN (199, 200, 246, 127);

-- SUBROTA: 4 - EGS-EDV
UPDATE ACTPP.TT_SUBROTA_AOP SET TTS_PNT_SUB = 'S' WHERE ACTPP.TT_SUBROTA_AOP.TTS_ID_AOP IN (248, 249, 281, 282); 

-- SUBROTA: 5 - EDV-EEL
UPDATE ACTPP.TT_SUBROTA_AOP SET TTS_PNT_SUB = 'S' WHERE ACTPP.TT_SUBROTA_AOP.TTS_ID_AOP IN (283, 284, 329, 330, 924, 925);

-- SUBROTA: 6 - ESQ-EEL 
UPDATE ACTPP.TT_SUBROTA_AOP SET TTS_PNT_SUB = 'S' WHERE ACTPP.TT_SUBROTA_AOP.TTS_ID_AOP IN (331, 332, 333, 334, 961, 962); 