--------------------------------------------------------------------------------------------------------
-- SISTEMA    	: ACTWEB - Sistema de Controle e Automação de Trens
-- TABELA       : TT_ROTA_AOP 
-- SEQUENCE    	: TT_ROTA_AOP_SEQUENCE
-- CRIADO    EM	: 04/10/2016
-- ANALISTA    	: DENER VIANA
-- AÇÃO			: Adicionando campo na tabela
--------------------------------------------------------------------------------------------------------

--DESFAZER
--ALTER TABLE TT_ROTA_AOP DROP COLUMN(TTR_PNT_RTA);

-- FAZER
ALTER TABLE ACTPP.TT_ROTA_AOP ADD (TTR_PNT_RTA		VARCHAR2(1 BYTE)	DEFAULT 'N'	NOT NULL);

-- ROTA: 1 - EBJ-ELL 
UPDATE ACTPP.TT_ROTA_AOP SET TTR_PNT_RTA = 'S' WHERE ACTPP.TT_ROTA_AOP.TTR_ID_AOP IN (1, 2, 167, 168, 222, 2223);

-- ROTA: 2 - EEL-EPW  
UPDATE ACTPP.TT_ROTA_AOP SET TTR_PNT_RTA = 'S' WHERE ACTPP.TT_ROTA_AOP.TTR_ID_AOP IN (169, 170, 172, 173);

INSERT INTO ACTPP.TT_ROTA_AOP VALUES (ACTPP.TT_ROTA_AOP_SEQUENCE.NEXTVAL, 2, SYSDATE, 86487, 120, 'S');
INSERT INTO ACTPP.TT_ROTA_AOP VALUES (ACTPP.TT_ROTA_AOP_SEQUENCE.NEXTVAL, 2, SYSDATE, 86488, 120, 'S');

-- ROTA: 3 - EEL-EGC  
UPDATE ACTPP.TT_ROTA_AOP SET TTR_PNT_RTA = 'S' WHERE ACTPP.TT_ROTA_AOP.TTR_ID_AOP IN (174, 175);

INSERT INTO ACTPP.TT_ROTA_AOP VALUES (ACTPP.TT_ROTA_AOP_SEQUENCE.NEXTVAL, 3, SYSDATE, 86487, 120, 'S');
INSERT INTO ACTPP.TT_ROTA_AOP VALUES (ACTPP.TT_ROTA_AOP_SEQUENCE.NEXTVAL, 3, SYSDATE, 86488, 120, 'S');

INSERT INTO ACTPP.TT_ROTA_AOP VALUES (ACTPP.TT_ROTA_AOP_SEQUENCE.NEXTVAL, 3, SYSDATE, 100350, 143, 'S');
INSERT INTO ACTPP.TT_ROTA_AOP VALUES (ACTPP.TT_ROTA_AOP_SEQUENCE.NEXTVAL, 3, SYSDATE, 20037, 143, 'S');

-- ROTA: 4 - EPW-ECE 
UPDATE ACTPP.TT_ROTA_AOP SET TTR_PNT_RTA = 'S' WHERE ACTPP.TT_ROTA_AOP.TTR_ID_AOP IN (176, 177, 179, 180);

-- ROTA: 5 - EPW-EWL 
UPDATE ACTPP.TT_ROTA_AOP SET TTR_PNT_RTA = 'S' WHERE ACTPP.TT_ROTA_AOP.TTR_ID_AOP IN (181, 182, 201, 202); 