--------------------------------------------------------------------------------------------------------
-- SISTEMA    	: ACTWEB - Sistema de Controle e Automação de Trens
-- TABELA       : SOLICITACAO_INTERDICAO 
-- SEQUENCE    	: SOLICITACAO_INTERDICAO_ID
-- CRIADO    EM	: 18/11/2016
-- ANALISTA    	: DENER VIANA
-- AÇÃO			: Adicionando campo na tabela
--------------------------------------------------------------------------------------------------------

--DESFAZER
--ALTER TABLE ACTPP.SOLICITACOES_LDL DROP COLUMN SO_LDL_DURACAO_AUTORIZADA;
--ALTER TABLE ACTPP.SOLICITACAO_INTERDICAO RENAME COLUMN SO_LDL_DURACAO_SOLICITADA TO SO_LDL_DURACAO;

--ALTER TABLE ACTWEB.SOLICITACAO_INTERDICAO DROP COLUMN SLT_DURACAO_AUTORIZADA;
--ALTER TABLE ACTWEB.SOLICITACAO_INTERDICAO RENAME COLUMN SLT_DURACAO_SOLICITADA TO SLT_DURACAO;


-- FAZER
ALTER TABLE ACTWEB.SOLICITACAO_INTERDICAO RENAME COLUMN SLT_DURACAO TO SLT_DURACAO_SOLICITADA;
ALTER TABLE ACTWEB.SOLICITACAO_INTERDICAO ADD (SLT_DURACAO_AUTORIZADA	NUMBER	NULL);

ALTER TABLE ACTPP.SOLICITACOES_LDL RENAME COLUMN SO_LDL_DURACAO TO SO_LDL_DURACAO_SOLICITADA;
ALTER TABLE ACTPP.SOLICITACOES_LDL ADD (SO_LDL_DURACAO_AUTORIZADA	NUMBER	NULL);


