drop table BANNERS;
drop sequence ACTWEB.BANNERS_ID;

CREATE TABLE BANNERS (    
  BNR_ID_BNR         NUMBER             NOT NULL PRIMARY KEY,
  BNR_NOM_ARQ        VARCHAR(255 BYTE)  NOT NULL,
  BNR_DSC_ARQ        VARCHAR(255 BYTE)  NULL,
  BNR_DTE_PUB        DATE               NOT NULL,
  BNR_ATV_SN         VARCHAR2(1 BYTE)   NOT NULL);  
 
CREATE SEQUENCE ACTWEB.BANNERS_ID
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
INSERT INTO BANNERS (BNR_ID_BNR, BNR_NOM_ARQ, BNR_DSC_ARQ, BNR_DTE_PUB, BNR_ATV_SN) VALUES (1, 'Banner01.png', 'Missão', TO_DATE('17/11/2015', 'DD/MM/YYYY'), 'S'); 
INSERT INTO BANNERS (BNR_ID_BNR, BNR_NOM_ARQ, BNR_DSC_ARQ, BNR_DTE_PUB, BNR_ATV_SN) VALUES (2, 'Banner02.png', 'Orgulho de Ser VL!', TO_DATE('17/11/2015', 'DD/MM/YYYY'), 'S');
INSERT INTO BANNERS (BNR_ID_BNR, BNR_NOM_ARQ, BNR_DSC_ARQ, BNR_DTE_PUB, BNR_ATV_SN) VALUES (3, 'Banner03.png', 'Visão', TO_DATE('17/11/2015', 'DD/MM/YYYY'), 'S');
INSERT INTO BANNERS (BNR_ID_BNR, BNR_NOM_ARQ, BNR_DSC_ARQ, BNR_DTE_PUB, BNR_ATV_SN) VALUES (4, 'Banner04.png', 'VL!', TO_DATE('17/11/2015', 'DD/MM/YYYY'), 'S');
INSERT INTO BANNERS (BNR_ID_BNR, BNR_NOM_ARQ, BNR_DSC_ARQ, BNR_DTE_PUB, BNR_ATV_SN) VALUES (5, 'Banner05.png', 'Logística Integrada', TO_DATE('17/11/2015', 'DD/MM/YYYY'), 'S');