--------------------------------------------------------------------------------------------------------
-- SISTEMA    	: ACTWEB 
-- TABELA       : SISTEMAS_MENUS
-- SEQUENCE    	: SISTEMAS_MENUS_ID
-- CRIADO    EM	: 15/04/2016
-- ANALISTA    	: DENER VIANA
--------------------------------------------------------------------------------------------------------

--drop table SISTEMAS_MENUS;
--drop sequence SISTEMAS_MENUS_ID;

CREATE TABLE SISTEMAS_MENUS (																	  	-- Cria a tabela trechos
  MEN_ID							NUMBER							NOT NULL PRIMARY KEY,		-- Identificador do menu
  SIS_ID							NUMBER							NOT NULL,								-- Identificador do sistema
  MEN_POSICAO					NUMBER							NOT NULL,								-- Posição do menu 
  MEN_NOME						VARCHAR2(070 BYTE)	NOT NULL,								-- Nome do menu
  MEN_ICONE_MOUSE_ON	VARCHAR2(200 BYTE)	NULL,										-- Endereço e nome do arquivo. Mouse posicionado no icone
  MEN_ICONE_MOUSE_OFF	VARCHAR2(200 BYTE)	NULL,										-- Endereço e nome do arquivo. Mouse posicionado fora do icone
	MEN_ARQUIVO					VARCHAR2(200 BYTE)	NULL,										-- Endereço e nome da página
	MEN_POPUP						VARCHAR2(1 BYTE)		NOT NULL,								-- Status [ S = Sim   | N = Não ]
	MEN_SUBMENU					VARCHAR2(1 BYTE)		NOT NULL, 							-- Status [ S = Sim   | N = Não ]
  MEN_ATIVO						VARCHAR2(1 BYTE)		NOT NULL);							-- Status [ S = Ativo | N = Inativo ]
 
CREATE SEQUENCE SISTEMAS_MENUS_ID																	-- Cria sequence (contador) da tabela
  START WITH 1                                                                                                    
  MAXVALUE 999999999999999999999999999                                                    
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
INSERT INTO SISTEMAS_MENUS (MEN_ID, SIS_ID, MEN_POSICAO, MEN_NOME, MEN_ICONE_MOUSE_ON, MEN_ICONE_MOUSE_OFF, MEN_ARQUIVO, MEN_POPUP, MEN_SUBMENU, MEN_ATIVO) VALUES (SISTEMAS_MENUS_ID.NEXTVAL, 1, 1, 'VMA', null, null, null, 'N', 'S', 'S');
INSERT INTO SISTEMAS_MENUS (MEN_ID, SIS_ID, MEN_POSICAO, MEN_NOME, MEN_ICONE_MOUSE_ON, MEN_ICONE_MOUSE_OFF, MEN_ARQUIVO, MEN_POPUP, MEN_SUBMENU, MEN_ATIVO) VALUES (SISTEMAS_MENUS_ID.NEXTVAL, 1, 2, 'Dados de Apoio', null, null, null, 'N', 'S', 'S');
INSERT INTO SISTEMAS_MENUS (MEN_ID, SIS_ID, MEN_POSICAO, MEN_NOME, MEN_ICONE_MOUSE_ON, MEN_ICONE_MOUSE_OFF, MEN_ARQUIVO, MEN_POPUP, MEN_SUBMENU, MEN_ATIVO) VALUES (SISTEMAS_MENUS_ID.NEXTVAL, 1, 3, 'GOP', null, null,'http://172.21.26.23/GOP/module/', 'S', 'N', 'S');
INSERT INTO SISTEMAS_MENUS (MEN_ID, SIS_ID, MEN_POSICAO, MEN_NOME, MEN_ICONE_MOUSE_ON, MEN_ICONE_MOUSE_OFF, MEN_ARQUIVO, MEN_POPUP, MEN_SUBMENU, MEN_ATIVO) VALUES (SISTEMAS_MENUS_ID.NEXTVAL, 1, 4, 'Gráfico de Trens', null, null, 'http://172.21.26.44:8080/e-graph-server/webGraphics/index', 'S', 'N', 'S');
INSERT INTO SISTEMAS_MENUS (MEN_ID, SIS_ID, MEN_POSICAO, MEN_NOME, MEN_ICONE_MOUSE_ON, MEN_ICONE_MOUSE_OFF, MEN_ARQUIVO, MEN_POPUP, MEN_SUBMENU, MEN_ATIVO) VALUES (SISTEMAS_MENUS_ID.NEXTVAL, 1, 5, 'Indicadores', null, null, null, 'N', 'S', 'S');
INSERT INTO SISTEMAS_MENUS (MEN_ID, SIS_ID, MEN_POSICAO, MEN_NOME, MEN_ICONE_MOUSE_ON, MEN_ICONE_MOUSE_OFF, MEN_ARQUIVO, MEN_POPUP, MEN_SUBMENU, MEN_ATIVO) VALUES (SISTEMAS_MENUS_ID.NEXTVAL, 1, 6, 'Locomotivas', null, null, null, 'N', 'S', 'S');
INSERT INTO SISTEMAS_MENUS (MEN_ID, SIS_ID, MEN_POSICAO, MEN_NOME, MEN_ICONE_MOUSE_ON, MEN_ICONE_MOUSE_OFF, MEN_ARQUIVO, MEN_POPUP, MEN_SUBMENU, MEN_ATIVO) VALUES (SISTEMAS_MENUS_ID.NEXTVAL, 1, 7, 'Macros', null, null, null, 'N', 'S', 'S');
INSERT INTO SISTEMAS_MENUS (MEN_ID, SIS_ID, MEN_POSICAO, MEN_NOME, MEN_ICONE_MOUSE_ON, MEN_ICONE_MOUSE_OFF, MEN_ARQUIVO, MEN_POPUP, MEN_SUBMENU, MEN_ATIVO) VALUES (SISTEMAS_MENUS_ID.NEXTVAL, 1, 8, 'Paineis', null, null, null, 'N', 'S', 'S');
INSERT INTO SISTEMAS_MENUS (MEN_ID, SIS_ID, MEN_POSICAO, MEN_NOME, MEN_ICONE_MOUSE_ON, MEN_ICONE_MOUSE_OFF, MEN_ARQUIVO, MEN_POPUP, MEN_SUBMENU, MEN_ATIVO) VALUES (SISTEMAS_MENUS_ID.NEXTVAL, 1, 9, 'Rádios', null, null, null, 'N', 'S', 'S');
INSERT INTO SISTEMAS_MENUS (MEN_ID, SIS_ID, MEN_POSICAO, MEN_NOME, MEN_ICONE_MOUSE_ON, MEN_ICONE_MOUSE_OFF, MEN_ARQUIVO, MEN_POPUP, MEN_SUBMENU, MEN_ATIVO) VALUES (SISTEMAS_MENUS_ID.NEXTVAL, 1, 10, 'Relatórios', null, null, null, 'N', 'S', 'S');
INSERT INTO SISTEMAS_MENUS (MEN_ID, SIS_ID, MEN_POSICAO, MEN_NOME, MEN_ICONE_MOUSE_ON, MEN_ICONE_MOUSE_OFF, MEN_ARQUIVO, MEN_POPUP, MEN_SUBMENU, MEN_ATIVO) VALUES (SISTEMAS_MENUS_ID.NEXTVAL, 1, 11, 'Restrições', null, null, null, 'N', 'S', 'S');
INSERT INTO SISTEMAS_MENUS (MEN_ID, SIS_ID, MEN_POSICAO, MEN_NOME, MEN_ICONE_MOUSE_ON, MEN_ICONE_MOUSE_OFF, MEN_ARQUIVO, MEN_POPUP, MEN_SUBMENU, MEN_ATIVO) VALUES (SISTEMAS_MENUS_ID.NEXTVAL, 1, 12, 'Telecomandadas', null, null, null, 'N', 'S', 'S');
INSERT INTO SISTEMAS_MENUS (MEN_ID, SIS_ID, MEN_POSICAO, MEN_NOME, MEN_ICONE_MOUSE_ON, MEN_ICONE_MOUSE_OFF, MEN_ARQUIVO, MEN_POPUP, MEN_SUBMENU, MEN_ATIVO) VALUES (SISTEMAS_MENUS_ID.NEXTVAL, 1, 13, 'THP', null, null, null, 'N', 'S', 'S');
INSERT INTO SISTEMAS_MENUS (MEN_ID, SIS_ID, MEN_POSICAO, MEN_NOME, MEN_ICONE_MOUSE_ON, MEN_ICONE_MOUSE_OFF, MEN_ARQUIVO, MEN_POPUP, MEN_SUBMENU, MEN_ATIVO) VALUES (SISTEMAS_MENUS_ID.NEXTVAL, 1, 14, 'Termômetros', null, null, null, 'N', 'S', 'S');
INSERT INTO SISTEMAS_MENUS (MEN_ID, SIS_ID, MEN_POSICAO, MEN_NOME, MEN_ICONE_MOUSE_ON, MEN_ICONE_MOUSE_OFF, MEN_ARQUIVO, MEN_POPUP, MEN_SUBMENU, MEN_ATIVO) VALUES (SISTEMAS_MENUS_ID.NEXTVAL, 1, 15, 'Usuários', null, null, null, 'N', 'S', 'S');
