
DROP TABLE ACTWEP.TIPO_INTERDICAO;
CREATE TABLE ACTWEP.TIPO_INTERDICAO
(
  TP_INT_ID      number              not null, -- Identificador do tipo de interdição
  TP_INT_CODIGO  number              not null, -- Código do tipo de interdição
  TP_INT_NOME    varchar2(30 byte)   not null, -- Nome ou descrição do tipo de interdição
  TP_INT_ATIVO   varchar2(1 byte)    not null  -- Se a interdição estiver ativa marque "S" caso contrario marque "N"
);

ALTER TABLE ACTWEP.TIPO_INTERDICAO ADD ( CONSTRAINT PK_TIPO_INTERDICAO PRIMARY KEY (TP_INT_ID) );

DROP   SEQUENCE ACTWEP.TIPO_INTERDICAO_ID;
CREATE SEQUENCE ACTWEP.TIPO_INTERDICAO_ID
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
INSERT INTO TIPO_INTERDICAO (TP_INT_ID, TP_INT_CODIGO, TP_INT_NOME, TP_INT_ATIVO) VALUES (TIPO_INTERDICAO_ID.NEXTVAL, 0, NULL, 'S' );
INSERT INTO TIPO_INTERDICAO (TP_INT_ID, TP_INT_CODIGO, TP_INT_NOME, TP_INT_ATIVO) VALUES (TIPO_INTERDICAO_ID.NEXTVAL, 1, 'Interdição Simples - INT', 'S' );
INSERT INTO TIPO_INTERDICAO (TP_INT_ID, TP_INT_CODIGO, TP_INT_NOME, TP_INT_ATIVO) VALUES (TIPO_INTERDICAO_ID.NEXTVAL, 2, 'Interdição Bloqueio - BLQ', 'S' );
INSERT INTO TIPO_INTERDICAO (TP_INT_ID, TP_INT_CODIGO, TP_INT_NOME, TP_INT_ATIVO) VALUES (TIPO_INTERDICAO_ID.NEXTVAL, 3, 'Interdição de LDL', 'S' );
  
