
drop table ACTWEB.GRUPOS;
drop sequence ACTWEB.GRUPOS_ID;

CREATE TABLE ACTWEB.GRUPOS (	
  GRU_ID_GRU         NUMBER, 
  GRU_NOME           VARCHAR2(30 BYTE), 
  GRU_ATIVO          VARCHAR2(1 BYTE));

ALTER TABLE ACTWEB.GRUPOS ADD ( CONSTRAINT PK_GRUPOS PRIMARY KEY (GRU_ID_GRU));

CREATE SEQUENCE ACTWEB.GRUPOS_ID
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
INSERT INTO GRUPOS (GRU_ID_GRU, GRU_NOME, GRU_ATIVO) VALUES (GRUPOS_ID.NEXTVAL, 'ACIDENTES', 'S');
INSERT INTO GRUPOS (GRU_ID_GRU, GRU_NOME, GRU_ATIVO) VALUES (GRUPOS_ID.NEXTVAL, 'CCO', 'S');
INSERT INTO GRUPOS (GRU_ID_GRU, GRU_NOME, GRU_ATIVO) VALUES (GRUPOS_ID.NEXTVAL, 'ELETROELETRÔNICA', 'S');
INSERT INTO GRUPOS (GRU_ID_GRU, GRU_NOME, GRU_ATIVO) VALUES (GRUPOS_ID.NEXTVAL, 'LOCOMOTIVA', 'S');
INSERT INTO GRUPOS (GRU_ID_GRU, GRU_NOME, GRU_ATIVO) VALUES (GRUPOS_ID.NEXTVAL, 'OBRAS CIVIS', 'S');
INSERT INTO GRUPOS (GRU_ID_GRU, GRU_NOME, GRU_ATIVO) VALUES (GRUPOS_ID.NEXTVAL, 'OPERAÇÃO DE TRENS', 'S');
INSERT INTO GRUPOS (GRU_ID_GRU, GRU_NOME, GRU_ATIVO) VALUES (GRUPOS_ID.NEXTVAL, 'PÁTIOS', 'S');
INSERT INTO GRUPOS (GRU_ID_GRU, GRU_NOME, GRU_ATIVO) VALUES (GRUPOS_ID.NEXTVAL, 'PORTOS/TERMINAIS', 'S');
INSERT INTO GRUPOS (GRU_ID_GRU, GRU_NOME, GRU_ATIVO) VALUES (GRUPOS_ID.NEXTVAL, 'VAGÕES', 'S');
INSERT INTO GRUPOS (GRU_ID_GRU, GRU_NOME, GRU_ATIVO) VALUES (GRUPOS_ID.NEXTVAL, 'VIA PERMANENTE', 'S');
