
drop table ACTWEB.TMP_MACROS;
drop sequence ACTWEB.TMP_MACROS_ID;

CREATE TABLE ACTWEB.TMP_MACROS (	
  TMP_ID_TMP         NUMBER            NOT NULL,
  TMP_MT_TMP         VARCHAR2(20 BYTE) NOT NULL,
  TMP_DT_TMP         DATE              NOT NULL,
  TMP_NN_MAC         NUMBER            NOT NULL, 
  TMP_ID_MCT         NUMBER            NULL, 
  TMP_NM_MCT         VARCHAR2(20 BYTE) NULL,
  TMP_ID_TRM         NUMBER            NULL,
  TMP_NM_TRM         VARCHAR2(20 BYTE) NULL);

ALTER TABLE ACTWEB.TMP_MACROS ADD ( CONSTRAINT PK_TMP_MACROS PRIMARY KEY (TMP_ID_TMP));

CREATE INDEX ACTWEB.TMC_DT_TMC on ACTWEB.TMP_MACROS('TMP_DT_TMC');

CREATE SEQUENCE ACTWEB.TMP_MACROS_ID
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  