
drop table ACTWEB.TIPO_LOCOMOTIVAS;
drop sequence ACTWEB.TIPO_LOCOMOTIVAS_ID;

CREATE TABLE ACTWEB.TIPO_LOCOMOTIVAS (	
  TIP_ID_TIP        NUMBER              NOT NULL,
  TIP_ATUALIZACAO   DATE                NOT NULL,
  TIP_DESCRICAO     VARCHAR2(50 BYTE)   NOT NULL,
  TIP_ATIVO_SN      VARCHAR2(1 BYTE)    NOT NULL);

ALTER TABLE ACTWEB.TIPO_LOCOMOTIVAS ADD ( CONSTRAINT PK_TIPO_LOCOMOTIVAS PRIMARY KEY (TIP_ID_TIP));

CREATE SEQUENCE ACTWEB.TIPO_LOCOMOTIVAS_ID
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  

INSERT INTO ACTWEB.TIPO_LOCOMOTIVAS (TIP_ID_TIP, TIP_ATUALIZACAO, TIP_DESCRICAO, TIP_ATIVO_SN) VALUES (TIPO_LOCOMOTIVAS_ID.NEXTVAL, SYSDATE, 'ALCO MX-620','S');
INSERT INTO ACTWEB.TIPO_LOCOMOTIVAS (TIP_ID_TIP, TIP_ATUALIZACAO, TIP_DESCRICAO, TIP_ATIVO_SN) VALUES (TIPO_LOCOMOTIVAS_ID.NEXTVAL, SYSDATE, 'ALCO SD4','S');
INSERT INTO ACTWEB.TIPO_LOCOMOTIVAS (TIP_ID_TIP, TIP_ATUALIZACAO, TIP_DESCRICAO, TIP_ATIVO_SN) VALUES (TIPO_LOCOMOTIVAS_ID.NEXTVAL, SYSDATE, 'GE BB-1234','S');
INSERT INTO ACTWEB.TIPO_LOCOMOTIVAS (TIP_ID_TIP, TIP_ATUALIZACAO, TIP_DESCRICAO, TIP_ATIVO_SN) VALUES (TIPO_LOCOMOTIVAS_ID.NEXTVAL, SYSDATE, 'GE BB-36','S');
INSERT INTO ACTWEB.TIPO_LOCOMOTIVAS (TIP_ID_TIP, TIP_ATUALIZACAO, TIP_DESCRICAO, TIP_ATIVO_SN) VALUES (TIPO_LOCOMOTIVAS_ID.NEXTVAL, SYSDATE, 'GE DASH 9-40','S');
INSERT INTO ACTWEB.TIPO_LOCOMOTIVAS (TIP_ID_TIP, TIP_ATUALIZACAO, TIP_DESCRICAO, TIP_ATIVO_SN) VALUES (TIPO_LOCOMOTIVAS_ID.NEXTVAL, SYSDATE, 'GE U20','S');
INSERT INTO ACTWEB.TIPO_LOCOMOTIVAS (TIP_ID_TIP, TIP_ATUALIZACAO, TIP_DESCRICAO, TIP_ATIVO_SN) VALUES (TIPO_LOCOMOTIVAS_ID.NEXTVAL, SYSDATE, 'GE U5','S');
INSERT INTO ACTWEB.TIPO_LOCOMOTIVAS (TIP_ID_TIP, TIP_ATUALIZACAO, TIP_DESCRICAO, TIP_ATIVO_SN) VALUES (TIPO_LOCOMOTIVAS_ID.NEXTVAL, SYSDATE, 'GM DDM 45','S');
INSERT INTO ACTWEB.TIPO_LOCOMOTIVAS (TIP_ID_TIP, TIP_ATUALIZACAO, TIP_DESCRICAO, TIP_ATIVO_SN) VALUES (TIPO_LOCOMOTIVAS_ID.NEXTVAL, SYSDATE, 'GM GT3','S');
INSERT INTO ACTWEB.TIPO_LOCOMOTIVAS (TIP_ID_TIP, TIP_ATUALIZACAO, TIP_DESCRICAO, TIP_ATIVO_SN) VALUES (TIPO_LOCOMOTIVAS_ID.NEXTVAL, SYSDATE, 'GM G8','S');
INSERT INTO ACTWEB.TIPO_LOCOMOTIVAS (TIP_ID_TIP, TIP_ATUALIZACAO, TIP_DESCRICAO, TIP_ATIVO_SN) VALUES (TIPO_LOCOMOTIVAS_ID.NEXTVAL, SYSDATE, 'GM SD40','S');
INSERT INTO ACTWEB.TIPO_LOCOMOTIVAS (TIP_ID_TIP, TIP_ATUALIZACAO, TIP_DESCRICAO, TIP_ATIVO_SN) VALUES (TIPO_LOCOMOTIVAS_ID.NEXTVAL, SYSDATE, 'GM SD70','S');
INSERT INTO ACTWEB.TIPO_LOCOMOTIVAS (TIP_ID_TIP, TIP_ATUALIZACAO, TIP_DESCRICAO, TIP_ATIVO_SN) VALUES (TIPO_LOCOMOTIVAS_ID.NEXTVAL, SYSDATE, 'GT46AC','S');
INSERT INTO ACTWEB.TIPO_LOCOMOTIVAS (TIP_ID_TIP, TIP_ATUALIZACAO, TIP_DESCRICAO, TIP_ATIVO_SN) VALUES (TIPO_LOCOMOTIVAS_ID.NEXTVAL, SYSDATE, 'MANUT. VIA','S');
INSERT INTO ACTWEB.TIPO_LOCOMOTIVAS (TIP_ID_TIP, TIP_ATUALIZACAO, TIP_DESCRICAO, TIP_ATIVO_SN) VALUES (TIPO_LOCOMOTIVAS_ID.NEXTVAL, SYSDATE, 'SD70ACE','S'); 
