
DROP   TABLE ACTWEB.TIPO_MANUTENCAO;
CREATE TABLE ACTWEB.TIPO_MANUTENCAO
(
  TP_MNT_ID      number              not null, -- Identificador do tipo de manutenção
  TP_MNT_CODIGO  number              not null, -- Código do tipo de manutenção
  TP_MNT_NOME    varchar2(30 byte)   not null, -- Nome ou descrição do tipo de manutenção
  TP_MNT_ATIVO   varchar2(1 byte)    not null  -- Se o tipo de manutenção estiver ativo marque "S" caso contrario marque "N"
);

ALTER TABLE ACTWEB.TIPO_MANUTENCAO ADD ( CONSTRAINT PK_TIPO_MANUTENCAO PRIMARY KEY (TP_MNT_ID) );

DROP   SEQUENCE ACTWEB.TIPO_MANUTENCAO_ID;
CREATE SEQUENCE ACTWEB.TIPO_MANUTENCAO_ID
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
INSERT INTO ACTWEB.TIPO_MANUTENCAO (TP_MNT_ID, TP_MNT_CODIGO, TP_MNT_NOME, TP_MNT_ATIVO) VALUES (TIPO_MANUTENCAO_ID.NEXTVAL, 0, NULL, 'S' );  
INSERT INTO ACTWEB.TIPO_MANUTENCAO (TP_MNT_ID, TP_MNT_CODIGO, TP_MNT_NOME, TP_MNT_ATIVO) VALUES (TIPO_MANUTENCAO_ID.NEXTVAL, 1, 'Programada', 'S' );
INSERT INTO ACTWEB.TIPO_MANUTENCAO (TP_MNT_ID, TP_MNT_CODIGO, TP_MNT_NOME, TP_MNT_ATIVO) VALUES (TIPO_MANUTENCAO_ID.NEXTVAL, 2, 'Tempo Disponível', 'S' );
INSERT INTO ACTWEB.TIPO_MANUTENCAO (TP_MNT_ID, TP_MNT_CODIGO, TP_MNT_NOME, TP_MNT_ATIVO) VALUES (TIPO_MANUTENCAO_ID.NEXTVAL, 3, 'Corretiva', 'S' );
  
