

DROP   TABLE ACTWEB.TIPO_CIRCULACAO;
CREATE TABLE ACTWEB.TIPO_CIRCULACAO
(
  TP_CIR_ID      number              not null, -- Identificador do tipo de circulação
  TP_CIR_CODIGO  number              not null, -- Código do tipo de circulação
  TP_CIR_NOME    varchar2(30 byte)   not null, -- Nome ou descrição do tipo de circulação
  TP_CIR_ATIVO   varchar2(1 byte)    not null  -- Se o tipo de circulação estiver ativo marque "S" caso contrario marque "N"
);

ALTER TABLE ACTWEB.TIPO_CIRCULACAO ADD ( CONSTRAINT PK_TIPO_CIRCULACAO PRIMARY KEY (TP_CIR_ID) );

DROP   SEQUENCE ACTWEB.TIPO_CIRCULACAO_ID;
CREATE SEQUENCE ACTWEB.TIPO_CIRCULACAO_ID
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
INSERT INTO ACTWEB.TIPO_CIRCULACAO (TP_CIR_ID, TP_CIR_CODIGO, TP_CIR_NOME, TP_CIR_ATIVO) VALUES (TIPO_CIRCULACAO_ID.NEXTVAL, 0, NULL, 'S' );  
INSERT INTO ACTWEB.TIPO_CIRCULACAO (TP_CIR_ID, TP_CIR_CODIGO, TP_CIR_NOME, TP_CIR_ATIVO) VALUES (TIPO_CIRCULACAO_ID.NEXTVAL, 1, 'Sem Restrição', 'S' );
INSERT INTO ACTWEB.TIPO_CIRCULACAO (TP_CIR_ID, TP_CIR_CODIGO, TP_CIR_NOME, TP_CIR_ATIVO) VALUES (TIPO_CIRCULACAO_ID.NEXTVAL, 2, 'Com Restrição', 'S' );
  
 