drop table DOWNLOADS;
drop sequence ACTWEB.DOWNLOADS_ID;

CREATE TABLE DOWNLOADS (    
  DWL_ID_DWL         NUMBER             NOT NULL PRIMARY KEY,
  DWL_MOD_SIS        NUMBER             NOT NULL,  
  DWL_NOM_ARQ        VARCHAR(255 BYTE)  NULL,
  DWL_DSC_ARQ        VARCHAR(255 BYTE)  NULL,
  DWL_VRS_ARQ        NUMBER(9, 2)       NULL, 
  DWL_PRV_ATZ        VARCHAR2(25 BYTE)  NULL, 
  DWL_ATZ_DWL        DATE               NOT NULL,
  DWL_LIB_SN         VARCHAR2(1 BYTE)   NOT NULL,
  DWL_ATV_SN         VARCHAR2(1 BYTE)   NOT NULL);  
 
CREATE SEQUENCE ACTWEB.DOWNLOADS_ID
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
INSERT INTO DOWNLOADS (DWL_ID_DWL, DWL_MOD_SIS, DWL_NOM_ARQ, DWL_DSC_ARQ, DWL_VRS_ARQ, DWL_PRV_ATZ, DWL_ATZ_DWL, DWL_LIB_SN, DWL_ATV_SN) VALUES (1, 1, 'OBC.zip', 'Versão Oficial Firmware + Arquivo GR', 3.24, 'SEM PREVISÃO', TO_DATE('17/09/2015', 'DD/MM/YYYY'), 'S', 'S'); 
INSERT INTO DOWNLOADS (DWL_ID_DWL, DWL_MOD_SIS, DWL_NOM_ARQ, DWL_DSC_ARQ, DWL_VRS_ARQ, DWL_PRV_ATZ, DWL_ATZ_DWL, DWL_LIB_SN, DWL_ATV_SN) VALUES (2, 1, 'malha.lib', 'Versão Oficial Mapa', 141, 'SEM PREVISÃO', TO_DATE('17/09/2015', 'DD/MM/YYYY'), 'S', 'S');
INSERT INTO DOWNLOADS (DWL_ID_DWL, DWL_MOD_SIS, DWL_NOM_ARQ, DWL_DSC_ARQ, DWL_VRS_ARQ, DWL_PRV_ATZ, DWL_ATZ_DWL, DWL_LIB_SN, DWL_ATV_SN) VALUES (3, 1, 'Login.zip', 'Login OBC', 0, 'SEM PREVISÃO', TO_DATE('17/09/2015', 'DD/MM/YYYY'), 'S', 'S');