
drop table ACTWEB.INFORMACAO_OBC;
drop sequence ACTWEB.INFORMACAO_OBC_ID;

CREATE TABLE ACTWEB.INFORMACAO_OBC (	
  OBC_ID_OBC         NUMBER, 
  OBC_ID_LOCO        NUMBER, 
  OBC_FROTA          VARCHAR2(6 BYTE), 
  OBC_CORREDOR       VARCHAR2(50 BYTE), 
  OBC_DT_ATUALIZACAO DATE,
  OBC_ATIVO_SN       VARCHAR2(1 BYTE));

ALTER TABLE ACTWEB.INFORMACAO_OBC ADD ( CONSTRAINT PK_OINFORMACAO_OBC PRIMARY KEY (OBC_ID_OBC) );

CREATE SEQUENCE ACTWEB.INFORMACAO_OBC_ID
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  