
drop table ACTWEB.PERFIS;
drop sequence ACTWEB.PERFIS_ID;

CREATE TABLE ACTWEB.PERFIS (    
  PER_ID_PER        NUMBER              NOT NULL,
  PER_ATUALIZACAO   DATE                NOT NULL,
  PER_DESCRICAO     VARCHAR2(50 BYTE)   NOT NULL,
  PER_ABREVIADO     VARCHAR2(10 BYTE)   NOT NULL,
  PER_ATIVO_SN      VARCHAR2(1 BYTE)    NOT NULL);

ALTER TABLE ACTWEB.PERFIS ADD ( CONSTRAINT PK_PERFIS PRIMARY KEY (PER_ID_PER));

CREATE SEQUENCE ACTWEB.PERFIS_ID
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


INSERT INTO ACTWEB.PERFIS (PER_ID_PER, PER_ATUALIZACAO, PER_DESCRICAO, PER_ABREVIADO, PER_ATIVO_SN) VALUES (PERFIS_ID.NEXTVAL, SYSDATE, 'ADMINISTRADOR', 'ADM','S');
INSERT INTO ACTWEB.PERFIS (PER_ID_PER, PER_ATUALIZACAO, PER_DESCRICAO, PER_ABREVIADO, PER_ATIVO_SN) VALUES (PERFIS_ID.NEXTVAL, SYSDATE, 'PADRÃO','PAD','S');
INSERT INTO ACTWEB.PERFIS (PER_ID_PER, PER_ATUALIZACAO, PER_DESCRICAO, PER_ABREVIADO, PER_ATIVO_SN) VALUES (PERFIS_ID.NEXTVAL, SYSDATE, 'CENTRO DE APOIO AO TREM','CAT','S');
INSERT INTO ACTWEB.PERFIS (PER_ID_PER, PER_ATUALIZACAO, PER_DESCRICAO, PER_ABREVIADO, PER_ATIVO_SN) VALUES (PERFIS_ID.NEXTVAL, SYSDATE, 'CENTRO DE TOMADA DE DECISÃO / HELPDESK','CTD','S');
INSERT INTO ACTWEB.PERFIS (PER_ID_PER, PER_ATUALIZACAO, PER_DESCRICAO, PER_ABREVIADO, PER_ATIVO_SN) VALUES (PERFIS_ID.NEXTVAL, SYSDATE, 'INSPETOR','INSP','S');
INSERT INTO ACTWEB.PERFIS (PER_ID_PER, PER_ATUALIZACAO, PER_DESCRICAO, PER_ABREVIADO, PER_ATIVO_SN) VALUES (PERFIS_ID.NEXTVAL, SYSDATE, 'OPERADOR DE VIA PERMANENTE','OP VP','S');
INSERT INTO ACTWEB.PERFIS (PER_ID_PER, PER_ATUALIZACAO, PER_DESCRICAO, PER_ABREVIADO, PER_ATIVO_SN) VALUES (PERFIS_ID.NEXTVAL, SYSDATE, 'OPERADOR ELETROELETRÔNICO','OP ELE','S');
INSERT INTO ACTWEB.PERFIS (PER_ID_PER, PER_ATUALIZACAO, PER_DESCRICAO, PER_ABREVIADO, PER_ATIVO_SN) VALUES (PERFIS_ID.NEXTVAL, SYSDATE, 'CENTRO DE CONTROLE DE EMERGÊNCIA','CCE','S');
INSERT INTO ACTWEB.PERFIS (PER_ID_PER, PER_ATUALIZACAO, PER_DESCRICAO, PER_ABREVIADO, PER_ATIVO_SN) VALUES (PERFIS_ID.NEXTVAL, SYSDATE, 'PROGRAMAÇÃO E CONTROLE DE MANUTENÇÃO','PCM','S');
INSERT INTO ACTWEB.PERFIS (PER_ID_PER, PER_ATUALIZACAO, PER_DESCRICAO, PER_ABREVIADO, PER_ATIVO_SN) VALUES (PERFIS_ID.NEXTVAL, SYSDATE, 'ADMINISTRADOR DE VIA PERMANENTE','ADM VP','S');
INSERT INTO ACTWEB.PERFIS (PER_ID_PER, PER_ATUALIZACAO, PER_DESCRICAO, PER_ABREVIADO, PER_ATIVO_SN) VALUES (PERFIS_ID.NEXTVAL, SYSDATE, 'ADMINISTRADOR ELETROELETRÔNICO','ADM ELE','S');
INSERT INTO ACTWEB.PERFIS (PER_ID_PER, PER_ATUALIZACAO, PER_DESCRICAO, PER_ABREVIADO, PER_ATIVO_SN) VALUES (PERFIS_ID.NEXTVAL, SYSDATE, 'OPERADOR VITORIA MINAS','OP VM','S');
INSERT INTO ACTWEB.PERFIS (PER_ID_PER, PER_ATUALIZACAO, PER_DESCRICAO, PER_ABREVIADO, PER_ATIVO_SN) VALUES (PERFIS_ID.NEXTVAL, SYSDATE, 'ADMINISTRADOR TELECON','ADM TEL','S');
