drop table OBC;
drop sequence ACTWEB.OBC_ID;

CREATE TABLE OBC (    
  OBC_ID_OBC         NUMBER             NOT NULL PRIMARY KEY,
  OBC_VRS_FIRM		 NUMBER(9, 2)       NULL,				
  OBC_VRS_MAPA       NUMBER             NULL,
  OBC_PRV_ATZ_FIRM   VARCHAR(25 BYTE)   NULL,
  OBC_PRV_ATZ_MAPA   VARCHAR(25 BYTE)   NULL, 
  OBC_DT_ATZ         DATE               NULL, 
  OBC_LIB_DWNL       VARCHAR2(1 BYTE)   NULL,
  OBC_ATIVO_SN       VARCHAR2(1 BYTE)   NOT NULL);  
 
CREATE SEQUENCE ACTWEB.OBC_ID
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  