--------------------------------------------------------------------------------------------------------
-- SISTEMA    	: ACTWEB 
-- TABELA       : TRECHOS
-- SEQUENCE    	: TRECHOS_ID
-- CRIADO    EM	: 08/04/2016
-- ANALISTA    	: DENER VIANA
--------------------------------------------------------------------------------------------------------

--drop table TRECHOS;
--drop sequence TRECHOS_ID;

CREATE TABLE TRECHOS (																				  -- Cria a tabela trechos
  TRE_ID             NUMBER             NOT NULL PRIMARY KEY,		-- Identificador do trechos
  TRE_NOME           VARCHAR2(70 BYTE)  NOT NULL,								-- Nome do trecho
  TRE_SIGLA          VARCHAR2(6 BYTE)   NOT NULL,								-- Sigla do trecho
  TRE_CADASTRO       DATE               NOT NULL,								-- Data de cadastro
  TRE_ATIVO          VARCHAR2(1 BYTE)   NOT NULL);							-- Status [ S = Ativo | N = Inativo ]
 
CREATE SEQUENCE TRECHOS_ID																			-- Cria sequence (contador) da tabela
  START WITH 1                                                                                                    
  MAXVALUE 999999999999999999999999999                                                    
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  

INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'EEL-EAU', 'TR_001', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'EBM-EIR', 'TR_002', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'EDV-EEB', 'TR_003', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'EAU-ZBL', 'TR_004', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'ZUB-EIA', 'TR_005', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'ZZZ-ZPG', 'TR_006', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'EAU-EBZ', 'TR_007', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'EOO-EPZ', 'TR_008', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'EGA-EJA', 'TR_009', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'ZAI-ZBA', 'TR_010', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'EGN-ECY', 'TR_011', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'EEL-EGC', 'TR_012', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'EPW-PST', 'TR_013', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'EGC-EMC', 'TR_014', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'EMC-DKY', 'TR_015', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'ECO-EPP', 'TR_016', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'EEL-ECL-SAM', 'TR_017', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'RESERVADO', 'TR_018', SYSDATE, 'N');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'DKY-DSF', 'TR_019', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'DPA-D', 'TR_020', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'DPA-3', 'TR_021', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'ZJJ-ZZZ', 'TR_022', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'ZRP-ZQP', 'TR_023', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'ZEG-ZBK', 'TR_024', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'ZYW', 'TR_025', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'ZAL-ZPS', 'TR_026', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'EOO-EGA', 'TR_027', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'ZAL-3', 'TR_028', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'ZPT-PCZ-MRS', 'TR_029', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'ZEM-ZYY-PSN', 'TR_030', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'ZYY-PCZ', 'TR_031', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'PFL-PPN', 'TR_032', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'PCR-PJL-PSU', 'TR_033', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'ZBV-ZBI', 'TR_034', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'ZBV-ZZZ', 'TR_035', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'EAO-CSN', 'TR_036', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'IAA-IFA', 'TR_037', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'EBJ-TIA', 'TR_038', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'PSN-3', 'TR_039', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'IPG-TUF', 'TR_040', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'ZYY3-PCX', 'TR_041', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'ZYY3-PCZ', 'TR_042', SYSDATE, 'S');
INSERT INTO TRECHOS (TRE_ID, TRE_NOME, TRE_SIGLA, TRE_CADASTRO, TRE_ATIVO) VALUES (TRECHOS_ID.NEXTVAL, 'GSZ-GRB', 'TR_043', SYSDATE, 'S');

