
drop table ACTWEB.SITUACAO_RADIOS;
drop sequence ACTWEB.SITUACAO_RADIOS_ID;

CREATE TABLE ACTWEB.SITUACAO_RADIOS (	
  SIT_ID_SIT        NUMBER              NOT NULL,
  SIT_ATUALIZACAO   DATE                NOT NULL,
  SIT_DESCRICAO     VARCHAR2(16 BYTE)   NOT NULL,
  SIT_ATIVO_SN      VARCHAR2(1 BYTE)    NOT NULL);

ALTER TABLE ACTWEB.SITUACAO_RADIOS ADD ( CONSTRAINT PK_SITUACAO_RADIOS PRIMARY KEY (SIT_ID_SIT));

CREATE SEQUENCE ACTWEB.SITUACAO_RADIOS_ID
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
  
INSERT INTO ACTWEB.SITUACAO_RADIOS (SIT_ID_SIT, SIT_ATUALIZACAO, SIT_DESCRICAO, SIT_ATIVO_SN) VALUES (SITUACAO_RADIOS_ID.NEXTVAL, SYSDATE, 'UM', 'S');  
INSERT INTO ACTWEB.SITUACAO_RADIOS (SIT_ID_SIT, SIT_ATUALIZACAO, SIT_DESCRICAO, SIT_ATIVO_SN) VALUES (SITUACAO_RADIOS_ID.NEXTVAL, SYSDATE, 'DOIS', 'S');  
INSERT INTO ACTWEB.SITUACAO_RADIOS (SIT_ID_SIT, SIT_ATUALIZACAO, SIT_DESCRICAO, SIT_ATIVO_SN) VALUES (SITUACAO_RADIOS_ID.NEXTVAL, SYSDATE, 'NENHUM', 'S');  
INSERT INTO ACTWEB.SITUACAO_RADIOS (SIT_ID_SIT, SIT_ATUALIZACAO, SIT_DESCRICAO, SIT_ATIVO_SN) VALUES (SITUACAO_RADIOS_ID.NEXTVAL, SYSDATE, 'VERIFICAR', 'S');  
