--Cria tablespace

CREATE TABLESPACE actsct DATAFILE 
  'D:\Oracle\product\11.2.0\dbhome_1\oradata\actsct' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE 10240M
LOGGING
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT MANUAL
FLASHBACK ON;



-- Cria usuario Actweb na tablespace actweb com permissoes necessarias

CREATE USER ACTSCT
  IDENTIFIED BY VALUES '1A902C72F31B9ED7'
  DEFAULT TABLESPACE ACTSCT
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for ACTSCT 
  GRANT CONNECT TO ACTSCT;
  GRANT RESOURCE TO ACTSCT;
  ALTER USER ACTSCT DEFAULT ROLE ALL;
  -- 10 System Privileges for ACTSCT 
  GRANT CREATE INDEXTYPE TO ACTSCT;
  GRANT UNLIMITED TABLESPACE TO ACTSCT;
  GRANT CREATE SEQUENCE TO ACTSCT;
  GRANT CREATE VIEW TO ACTSCT;
  GRANT CREATE TRIGGER TO ACTSCT;
  GRANT CREATE TYPE TO ACTSCT;
  GRANT CREATE PROCEDURE TO ACTSCT;
  GRANT CREATE JOB TO ACTSCT;
  GRANT CREATE TABLE TO ACTSCT;
  GRANT CREATE USER TO ACTSCT;
  GRANT CREATE SESSION TO ACTSCT;
  GRANT READ, WRITE ON DIRECTORY DATA_PUMP_DIR TO ACTSCT;
  GRANT SELECT ANY DICTIONARY TO ACTSCT;
  GRANT ADVISOR TO ACTSCT;
  GRANT ADMINISTER SQL TUNING SET TO ACTSCT;  
  -- 9 Tablespace Quotas for ACTSCT 
  ALTER USER ACTSCT QUOTA UNLIMITED ON ACTTRPI;
  ALTER USER ACTSCT QUOTA UNLIMITED ON ACTTRGD;
  ALTER USER ACTSCT QUOTA UNLIMITED ON ACTTRPD;
  ALTER USER ACTSCT QUOTA UNLIMITED ON ACTCADD;
  ALTER USER ACTSCT QUOTA UNLIMITED ON ACTHSTD;
  ALTER USER ACTSCT QUOTA UNLIMITED ON ACTCADI;
  ALTER USER ACTSCT QUOTA UNLIMITED ON ACTHSTI;
  ALTER USER ACTSCT QUOTA UNLIMITED ON ACTSCT;
  ALTER USER ACTSCT QUOTA UNLIMITED ON ACTTRGI;
  ALTER USER ACTSCT IDENTIFIED BY actsct;  
  
  
  -- criando a tabela usuarios 
  


