
drop table ACTWEB.MOTIVO_LDL;
drop sequence ACTWEB.MOTIVO_LDL_ID;

CREATE TABLE ACTWEB.MOTIVO_LDL (    
  MTV_ID_MTV         NUMBER								NOT NULL, 
  MTV_CODIGO         VARCHAR2(04 BYTE)		NULL, 
  MTV_DESCRICAO      VARCHAR2(50 BYTE)		NOT NULL, 
  MTV_ATIVO          VARCHAR2(01 BYTE)		NOT NULL);

ALTER TABLE ACTWEB.MOTIVO_LDL ADD ( CONSTRAINT PK_MOTIVO_LDL PRIMARY KEY (MTV_ID_MTV));

CREATE SEQUENCE ACTWEB.MOTIVO_LDL_ID
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, 'ANV','AMV com anomalia na linha de Desvio','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, null,'AMV com anomalia na linha Principal','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, null,'Anomalia em ponte','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, 'ARV','Árvore na Via','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, null,'Balanço / Linha Desnivelada','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, 'BIT','Bitola Aberta','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, null,'Bueiro Quebrado','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, 'MAN','Defeito / Manutenção - Eletroeletrônica','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, null,'Faixa para manutenção de AMV','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, null,'Faixa para manutenção de Bitola','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, null,'Faixa para manutenção de Flambagem','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, null,'Faixa para manutenção de Juntas / Fixações','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, null,'Faixa para manutenção de Solda','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, null,'Faixa para troca de Trilho Quebrado / Trincado','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, null,'Faixa para troca de Dormentes','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, null,'Faixa para trabalho com Retroescavadeira','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, null,'Fixação Deficiente ','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, 'MAO','Manobra','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, 'SOL','Solicit. Interd','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, 'FLA','Flambagem / Gancho','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, null,'Fuga de Aterro / Lastro','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, null,'Incêndio às margens da via','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, null,'Incêndio em equipamentos (locomotiva / auto)','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, null,'Junta com abertura','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, null,'Junta com anomalia (Tala quebrada ou trincada)','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, null,'Lastro com Anomalia (Laqueado / Contaminado)','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, null,'Linha Alagada','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, 'MAO','Manobra','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, null,'Ocorrência Ferroviária','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, null,'Operação','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, null,'Pátio do Cliente','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, null,'Pedra na via','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, null,'Queda de barreira','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, null,'Restrição de Via','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, null,'Solda Quebrada','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, null,'Superelevação','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, 'VAN','Terceiros (Vandalismo / imprudência)','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, null,'Terra na via','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, null,'Torção','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, null,'Trilho patinado','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, 'DTQ','Trilho Quebrado','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, null,'Trilho Trincado - Ronda ou Trem','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, null,'Trilho Trincado – Ultrassom','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, null,'Operação CCO','S');
INSERT INTO MOTIVO_LDL (MTV_ID_MTV, MTV_CODIGO, MTV_DESCRICAO, MTV_ATIVO) VALUES (MOTIVO_LDL_ID.NEXTVAL, 'NAD','Nada','S');



