--Cria tablespace

--DROP TABLESPACE ACTCADD INCLUDING CONTENTS CASCADE CONSTRAINTS;
--DROP TABLESPACE ACTCADI INCLUDING CONTENTS CASCADE CONSTRAINTS;
--DROP TABLESPACE ACTHSTD INCLUDING CONTENTS CASCADE CONSTRAINTS;
--DROP TABLESPACE ACTHSTI INCLUDING CONTENTS CASCADE CONSTRAINTS;
--DROP TABLESPACE ACTPP INCLUDING CONTENTS CASCADE CONSTRAINTS;
--DROP TABLESPACE ACTTRGD INCLUDING CONTENTS CASCADE CONSTRAINTS;
--DROP TABLESPACE ACTTRGI INCLUDING CONTENTS CASCADE CONSTRAINTS;
--DROP TABLESPACE ACTTRPD INCLUDING CONTENTS CASCADE CONSTRAINTS;
--DROP TABLESPACE ACTTRPI INCLUDING CONTENTS CASCADE CONSTRAINTS;
--DROP TABLESPACE ACTTUNL INCLUDING CONTENTS CASCADE CONSTRAINTS;


CREATE TABLESPACE ACTCADD DATAFILE 
  'D:\Oracle\product\11.2.0\dbhome_1\oradata\ACTCADD' SIZE 100M REUSE AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE ACTCADI DATAFILE 
  'D:\Oracle\product\11.2.0\dbhome_1\oradata\ACTCADI' SIZE 100M REUSE AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE ACTHSTD DATAFILE 
  'D:\Oracle\product\11.2.0\dbhome_1\oradata\ACTHSTD' SIZE 100M REUSE AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE ACTHSTI DATAFILE 
  'D:\Oracle\product\11.2.0\dbhome_1\oradata\ACTHSTI' SIZE 100M REUSE AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE ACTPP DATAFILE 
  'D:\Oracle\product\11.2.0\dbhome_1\oradata\ACTPP' SIZE 100M REUSE AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE ACTTRGD DATAFILE 
  'D:\Oracle\product\11.2.0\dbhome_1\oradata\ACTTRGD' SIZE 100M REUSE AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE ACTTRGI DATAFILE 
  'D:\Oracle\product\11.2.0\dbhome_1\oradata\ACTTRGI' SIZE 100M REUSE AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE ACTTRPD DATAFILE 
  'D:\Oracle\product\11.2.0\dbhome_1\oradata\ACTTRPD' SIZE 100M REUSE AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE ACTTRPI DATAFILE 
  'D:\Oracle\product\11.2.0\dbhome_1\oradata\ACTTRPI' SIZE 100M REUSE AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE ACTTUNL DATAFILE 
  'D:\Oracle\product\11.2.0\dbhome_1\oradata\ACTTUNL' SIZE 100M REUSE AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


-- Cria usuario Actweb na tablespace actweb com permissoes necessarias

CREATE USER ACTPP
  IDENTIFIED BY VALUES '1A902C72F31B9ED7'
  DEFAULT TABLESPACE ACTPP
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for ACTPP 
  GRANT CONNECT TO ACTPP;
  GRANT RESOURCE TO ACTPP;
  ALTER USER ACTPP DEFAULT ROLE ALL;
  -- 10 System Privileges for ACTPP 
  GRANT CREATE INDEXTYPE TO ACTPP;
  GRANT UNLIMITED TABLESPACE TO ACTPP;
  GRANT CREATE SEQUENCE TO ACTPP;
  GRANT CREATE VIEW TO ACTPP;
  GRANT CREATE TRIGGER TO ACTPP;
  GRANT CREATE TYPE TO ACTPP;
  GRANT CREATE PROCEDURE TO ACTPP;
  GRANT CREATE JOB TO ACTPP;
  GRANT CREATE TABLE TO ACTPP;
  GRANT CREATE USER TO ACTPP;
  GRANT CREATE SESSION TO ACTPP;
  GRANT IMP_FULL_DATABASE to ACTPP;
  GRANT READ, WRITE ON DIRECTORY DATA_PUMP_DIR TO ACTPP;
  GRANT SELECT_CATALOG_ROLE TO ACTPP;
  GRANT SELECT ANY DICTIONARY TO ACTPP;
  GRANT ADVISOR TO ACTPP;
  GRANT ADMINISTER SQL TUNING SET TO ACTPP;  
  -- 9 Tablespace Quotas for ACTPP 
  ALTER USER ACTPP QUOTA UNLIMITED ON ACTTRPI;
  ALTER USER ACTPP QUOTA UNLIMITED ON ACTTRGD;
  ALTER USER ACTPP QUOTA UNLIMITED ON ACTTRPD;
  ALTER USER ACTPP QUOTA UNLIMITED ON ACTCADD;
  ALTER USER ACTPP QUOTA UNLIMITED ON ACTHSTD;
  ALTER USER ACTPP QUOTA UNLIMITED ON ACTCADI;
  ALTER USER ACTPP QUOTA UNLIMITED ON ACTHSTI;
  ALTER USER ACTPP QUOTA UNLIMITED ON ACTPP;
  ALTER USER ACTPP QUOTA UNLIMITED ON ACTTRGI;
  ALTER USER ACTPP IDENTIFIED BY engesis;  
  
  -- criando a tabela usuarios 
  


