drop table ACTWEB.CORREDORES;
drop sequence ACTWEB.CORREDORES_ID;

CREATE TABLE ACTWEB.CORREDORES (	
  COR_ID_COR        NUMBER              NOT NULL, 
  COR_ATUALIZACAO   DATE                NOT NULL, 
  COR_DESCRICAO     VARCHAR2(20 BYTE)   NOT NULL, 
  COR_ATIVO_SN      VARCHAR2(1 BYTE)    NOT NULL);

ALTER TABLE ACTWEB.CORREDORES ADD ( CONSTRAINT PK_CORREDORES PRIMARY KEY (COR_ID_COR));

CREATE SEQUENCE ACTWEB.CORREDORES_ID
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
INSERT INTO ACTWEB.CORREDORES (COR_ID_COR, COR_ATUALIZACAO, COR_DESCRICAO, COR_ATIVO_SN) VALUES (1, SYSDATE, 'Baixada', 'S');
INSERT INTO ACTWEB.CORREDORES (COR_ID_COR, COR_ATUALIZACAO, COR_DESCRICAO, COR_ATIVO_SN) VALUES (2, SYSDATE, 'Centro Leste', 'S');
INSERT INTO ACTWEB.CORREDORES (COR_ID_COR, COR_ATUALIZACAO, COR_DESCRICAO, COR_ATIVO_SN) VALUES (3, SYSDATE, 'Centro Norte', 'S');
INSERT INTO ACTWEB.CORREDORES (COR_ID_COR, COR_ATUALIZACAO, COR_DESCRICAO, COR_ATIVO_SN) VALUES (4, SYSDATE, 'Centro Sudeste', 'S');
INSERT INTO ACTWEB.CORREDORES (COR_ID_COR, COR_ATUALIZACAO, COR_DESCRICAO, COR_ATIVO_SN) VALUES (5, SYSDATE, 'Minas Bahia', 'S');
INSERT INTO ACTWEB.CORREDORES (COR_ID_COR, COR_ATUALIZACAO, COR_DESCRICAO, COR_ATIVO_SN) VALUES (6, SYSDATE, 'Minas Rio', 'S');