
drop table ACTWEB.DISPLAY;
drop sequence ACTWEB.DISPLAY_ID;

CREATE TABLE ACTWEB.DISPLAY (	
  DSP_ID_DSP        NUMBER              NOT NULL,
  DSP_MENSAGEM      VARCHAR2(1024 BYTE) NOT NULL,
  DSP_DATA          DATE                NOT NULL,
  DSP_ATIVO_SN      VARCHAR2(1 BYTE)    NOT NULL);

ALTER TABLE ACTWEB.DISPLAY ADD ( CONSTRAINT PK_DISPLAY PRIMARY KEY (DSP_ID_DSP));

CREATE INDEX ACTWEB.DSP_DATA on ACTWEB.DISPLAY('DSP_DATA');

CREATE SEQUENCE ACTWEB.DISPLAY_ID
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
COMMIT;  