

INSERT INTO MACRODEFINITION_MAC ( 
			MAC_NUM_ID,								-- INTEGER
			ACC_NUM_ACCOUNTNUMBER,		-- INTEGER
			MAC_NUM_MACRONUMBER,			-- INTEGER
			MAC_NUM_MACROVERSION,			-- INTEGER
			MAC_BOL_ISFORWARD,				-- INTEGER
			MAC_BOL_AUTOPRINT,				-- INTEGER
			MAC_NOM_MACRONAME, 				-- VARCHAR2(25 CHAR)
			MAC_DES_MACRODESCRIPTION, -- VARCHAR2(300 CHAR)
			MAC_DTM_CREATEDATE,				-- DATE
			MAC_DTM_DEFINITIONDATE,		-- DATE
			MAC_TXT_MACRODEFINITION, 	-- VARCHAR2(3000 CHAR)
			MAC_NUM_DATATYPE,					-- INTEGER
			MAC_NUM_MACROTYPE,				-- INTEGER
			MAC_NUM_REPLYMACRO,				-- INTEGER
			MAC_NUM_COLOR,						-- INTEGER
			MAC_NUM_ICONID,						-- INTEGER
			MAC_BOL_FORWARD)					-- INTEGER
VALUES (569, 61643776, 16, 6, 0, 0, 'Macro_16', NULL, SYSDATE, SYSDATE, 
'---------ENTRADA DE MAQUINISTA--------\\MATRICULA       _13308 \TREM                   _13304\OS                         _13108\ORIGEM              _13302\\                           FUNCAO  DATA       HORA\SOBREAVISO    _00203   _00808  _01105 \PRONTIDAO      _00203   _00808  _01105    DE          PARA\PASSE                _00203   _00808  _01105    _13302 _13302\AG. TREM          _00203   _00808  _01105    DESTINO\EM TREM           _00203   _00808  _01105    _13303\', 0, 2, 0, 0, 0, 0);

INSERT INTO MACROFIELDDEFINITION_MFL (
     MAC_NUM_ID,								-- INTEGER  
     MFL_NOM_FIELDNAME,         -- VARCHAR2(20 BYTE)
     MFL_NUM_FIELDTYPE,   			-- INTEGER
     MFL_NUM_FIELDLENGTH, 			-- INTEGER
     MFL_BOL_MUSTBEFILLED,			-- VARCHAR2(20 BYTE)
     MFL_DES_FIELDLABEL)				-- VARCHAR2(255 BYTE)
VALUES (569, 'Field 01', 38, 8, 'True', '\MATRICULA:');

INSERT INTO MACROFIELDDEFINITION_MFL (
     MAC_NUM_ID,								-- INTEGER  
     MFL_NOM_FIELDNAME,         -- VARCHAR2(20 BYTE)
     MFL_NUM_FIELDTYPE,   			-- INTEGER
     MFL_NUM_FIELDLENGTH, 			-- INTEGER
     MFL_BOL_MUSTBEFILLED,			-- VARCHAR2(20 BYTE)
     MFL_DES_FIELDLABEL)				-- VARCHAR2(255 BYTE)
VALUES (569, 'Field 02', 38, 8, 'True', '\TREM:');

INSERT INTO MACROFIELDDEFINITION_MFL (
     MAC_NUM_ID,								-- INTEGER  
     MFL_NOM_FIELDNAME,         -- VARCHAR2(20 BYTE)
     MFL_NUM_FIELDTYPE,   			-- INTEGER
     MFL_NUM_FIELDLENGTH, 			-- INTEGER
     MFL_BOL_MUSTBEFILLED,			-- VARCHAR2(20 BYTE)
     MFL_DES_FIELDLABEL)				-- VARCHAR2(255 BYTE)
VALUES (569, 'Field 03', 38, 8, 'True', '\OS:');

INSERT INTO MACROFIELDDEFINITION_MFL (
     MAC_NUM_ID,								-- INTEGER  
     MFL_NOM_FIELDNAME,         -- VARCHAR2(20 BYTE)
     MFL_NUM_FIELDTYPE,   			-- INTEGER
     MFL_NUM_FIELDLENGTH, 			-- INTEGER
     MFL_BOL_MUSTBEFILLED,			-- VARCHAR2(20 BYTE)
     MFL_DES_FIELDLABEL)				-- VARCHAR2(255 BYTE)
VALUES (569, 'Field 04', 38, 5, 'True', '\ORIGEM:');

INSERT INTO MACROFIELDDEFINITION_MFL (
     MAC_NUM_ID,								-- INTEGER  
     MFL_NOM_FIELDNAME,         -- VARCHAR2(20 BYTE)
     MFL_NUM_FIELDTYPE,   			-- INTEGER
     MFL_NUM_FIELDLENGTH, 			-- INTEGER
     MFL_BOL_MUSTBEFILLED,			-- VARCHAR2(20 BYTE)
     MFL_DES_FIELDLABEL)				-- VARCHAR2(255 BYTE)
VALUES (569, 'Field 05', 38, 5, 'True', '\FUNÇÃO_1:');

INSERT INTO MACROFIELDDEFINITION_MFL (
     MAC_NUM_ID,								-- INTEGER  
     MFL_NOM_FIELDNAME,         -- VARCHAR2(20 BYTE)
     MFL_NUM_FIELDTYPE,   			-- INTEGER
     MFL_NUM_FIELDLENGTH, 			-- INTEGER
     MFL_BOL_MUSTBEFILLED,			-- VARCHAR2(20 BYTE)
     MFL_DES_FIELDLABEL)				-- VARCHAR2(255 BYTE)
VALUES (569, 'Field 06', 38, 5, 'True', '\DATA_1:');

INSERT INTO MACROFIELDDEFINITION_MFL (
     MAC_NUM_ID,								-- INTEGER  
     MFL_NOM_FIELDNAME,         -- VARCHAR2(20 BYTE)
     MFL_NUM_FIELDTYPE,   			-- INTEGER
     MFL_NUM_FIELDLENGTH, 			-- INTEGER
     MFL_BOL_MUSTBEFILLED,			-- VARCHAR2(20 BYTE)
     MFL_DES_FIELDLABEL)				-- VARCHAR2(255 BYTE)
VALUES (569, 'Field 07', 38, 5, 'True', '\HORA_1:'); 

INSERT INTO MACROFIELDDEFINITION_MFL (
     MAC_NUM_ID,								-- INTEGER  
     MFL_NOM_FIELDNAME,         -- VARCHAR2(20 BYTE)
     MFL_NUM_FIELDTYPE,   			-- INTEGER
     MFL_NUM_FIELDLENGTH, 			-- INTEGER
     MFL_BOL_MUSTBEFILLED,			-- VARCHAR2(20 BYTE)
     MFL_DES_FIELDLABEL)				-- VARCHAR2(255 BYTE)
VALUES (569, 'Field 08', 38, 5, 'True', '\FUNÇÃO_2:');

INSERT INTO MACROFIELDDEFINITION_MFL (
     MAC_NUM_ID,								-- INTEGER  
     MFL_NOM_FIELDNAME,         -- VARCHAR2(20 BYTE)
     MFL_NUM_FIELDTYPE,   			-- INTEGER
     MFL_NUM_FIELDLENGTH, 			-- INTEGER
     MFL_BOL_MUSTBEFILLED,			-- VARCHAR2(20 BYTE)
     MFL_DES_FIELDLABEL)				-- VARCHAR2(255 BYTE)
VALUES (569, 'Field 09', 38, 5, 'True', '\DATA_2:');

INSERT INTO MACROFIELDDEFINITION_MFL (
     MAC_NUM_ID,								-- INTEGER  
     MFL_NOM_FIELDNAME,         -- VARCHAR2(20 BYTE)
     MFL_NUM_FIELDTYPE,   			-- INTEGER
     MFL_NUM_FIELDLENGTH, 			-- INTEGER
     MFL_BOL_MUSTBEFILLED,			-- VARCHAR2(20 BYTE)
     MFL_DES_FIELDLABEL)				-- VARCHAR2(255 BYTE)
VALUES (569, 'Field 10', 38, 5, 'True', '\HORA_2:'); 

INSERT INTO MACROFIELDDEFINITION_MFL (
     MAC_NUM_ID,								-- INTEGER  
     MFL_NOM_FIELDNAME,         -- VARCHAR2(20 BYTE)
     MFL_NUM_FIELDTYPE,   			-- INTEGER
     MFL_NUM_FIELDLENGTH, 			-- INTEGER
     MFL_BOL_MUSTBEFILLED,			-- VARCHAR2(20 BYTE)
     MFL_DES_FIELDLABEL)				-- VARCHAR2(255 BYTE)
VALUES (569, 'Field 11', 38, 5, 'True', '\FUNÇÃO_3:');

INSERT INTO MACROFIELDDEFINITION_MFL (
     MAC_NUM_ID,								-- INTEGER  
     MFL_NOM_FIELDNAME,         -- VARCHAR2(20 BYTE)
     MFL_NUM_FIELDTYPE,   			-- INTEGER
     MFL_NUM_FIELDLENGTH, 			-- INTEGER
     MFL_BOL_MUSTBEFILLED,			-- VARCHAR2(20 BYTE)
     MFL_DES_FIELDLABEL)				-- VARCHAR2(255 BYTE)
VALUES (569, 'Field 12', 38, 5, 'True', '\DATA_3:');

INSERT INTO MACROFIELDDEFINITION_MFL (
     MAC_NUM_ID,								-- INTEGER  
     MFL_NOM_FIELDNAME,         -- VARCHAR2(20 BYTE)
     MFL_NUM_FIELDTYPE,   			-- INTEGER
     MFL_NUM_FIELDLENGTH, 			-- INTEGER
     MFL_BOL_MUSTBEFILLED,			-- VARCHAR2(20 BYTE)
     MFL_DES_FIELDLABEL)				-- VARCHAR2(255 BYTE)
VALUES (569, 'Field 13', 38, 5, 'True', '\HORA_3:');

INSERT INTO MACROFIELDDEFINITION_MFL (
     MAC_NUM_ID,								-- INTEGER  
     MFL_NOM_FIELDNAME,         -- VARCHAR2(20 BYTE)
     MFL_NUM_FIELDTYPE,   			-- INTEGER
     MFL_NUM_FIELDLENGTH, 			-- INTEGER
     MFL_BOL_MUSTBEFILLED,			-- VARCHAR2(20 BYTE)
     MFL_DES_FIELDLABEL)				-- VARCHAR2(255 BYTE)
VALUES (569, 'Field 14', 38, 5, 'True', '\DE:');

INSERT INTO MACROFIELDDEFINITION_MFL (
     MAC_NUM_ID,								-- INTEGER  
     MFL_NOM_FIELDNAME,         -- VARCHAR2(20 BYTE)
     MFL_NUM_FIELDTYPE,   			-- INTEGER
     MFL_NUM_FIELDLENGTH, 			-- INTEGER
     MFL_BOL_MUSTBEFILLED,			-- VARCHAR2(20 BYTE)
     MFL_DES_FIELDLABEL)				-- VARCHAR2(255 BYTE)
VALUES (569, 'Field 15', 38, 5, 'True', '\PARA:');


INSERT INTO MACROFIELDDEFINITION_MFL (
     MAC_NUM_ID,								-- INTEGER  
     MFL_NOM_FIELDNAME,         -- VARCHAR2(20 BYTE)
     MFL_NUM_FIELDTYPE,   			-- INTEGER
     MFL_NUM_FIELDLENGTH, 			-- INTEGER
     MFL_BOL_MUSTBEFILLED,			-- VARCHAR2(20 BYTE)
     MFL_DES_FIELDLABEL)				-- VARCHAR2(255 BYTE)
VALUES (569, 'Field 16', 38, 5, 'True', '\FUNÇÃO_4:');

INSERT INTO MACROFIELDDEFINITION_MFL (
     MAC_NUM_ID,								-- INTEGER  
     MFL_NOM_FIELDNAME,         -- VARCHAR2(20 BYTE)
     MFL_NUM_FIELDTYPE,   			-- INTEGER
     MFL_NUM_FIELDLENGTH, 			-- INTEGER
     MFL_BOL_MUSTBEFILLED,			-- VARCHAR2(20 BYTE)
     MFL_DES_FIELDLABEL)				-- VARCHAR2(255 BYTE)
VALUES (569, 'Field 17', 38, 5, 'True', '\DATA_4:');

INSERT INTO MACROFIELDDEFINITION_MFL (
     MAC_NUM_ID,								-- INTEGER  
     MFL_NOM_FIELDNAME,         -- VARCHAR2(20 BYTE)
     MFL_NUM_FIELDTYPE,   			-- INTEGER
     MFL_NUM_FIELDLENGTH, 			-- INTEGER
     MFL_BOL_MUSTBEFILLED,			-- VARCHAR2(20 BYTE)
     MFL_DES_FIELDLABEL)				-- VARCHAR2(255 BYTE)
VALUES (569, 'Field 18', 38, 5, 'True', '\HORA_4:');

INSERT INTO MACROFIELDDEFINITION_MFL (
     MAC_NUM_ID,								-- INTEGER  
     MFL_NOM_FIELDNAME,         -- VARCHAR2(20 BYTE)
     MFL_NUM_FIELDTYPE,   			-- INTEGER
     MFL_NUM_FIELDLENGTH, 			-- INTEGER
     MFL_BOL_MUSTBEFILLED,			-- VARCHAR2(20 BYTE)
     MFL_DES_FIELDLABEL)				-- VARCHAR2(255 BYTE)
VALUES (569, 'Field 19', 38, 5, 'True', '\FUNÇÃO_5:');

INSERT INTO MACROFIELDDEFINITION_MFL (
     MAC_NUM_ID,								-- INTEGER  
     MFL_NOM_FIELDNAME,         -- VARCHAR2(20 BYTE)
     MFL_NUM_FIELDTYPE,   			-- INTEGER
     MFL_NUM_FIELDLENGTH, 			-- INTEGER
     MFL_BOL_MUSTBEFILLED,			-- VARCHAR2(20 BYTE)
     MFL_DES_FIELDLABEL)				-- VARCHAR2(255 BYTE)
VALUES (569, 'Field 20', 38, 5, 'True', '\DATA_5:');

INSERT INTO MACROFIELDDEFINITION_MFL (
     MAC_NUM_ID,								-- INTEGER  
     MFL_NOM_FIELDNAME,         -- VARCHAR2(20 BYTE)
     MFL_NUM_FIELDTYPE,   			-- INTEGER
     MFL_NUM_FIELDLENGTH, 			-- INTEGER
     MFL_BOL_MUSTBEFILLED,			-- VARCHAR2(20 BYTE)
     MFL_DES_FIELDLABEL)				-- VARCHAR2(255 BYTE)
VALUES (569, 'Field 21', 38, 5, 'True', '\HORA_5:');

INSERT INTO MACROFIELDDEFINITION_MFL (
     MAC_NUM_ID,								-- INTEGER  
     MFL_NOM_FIELDNAME,         -- VARCHAR2(20 BYTE)
     MFL_NUM_FIELDTYPE,   			-- INTEGER
     MFL_NUM_FIELDLENGTH, 			-- INTEGER
     MFL_BOL_MUSTBEFILLED,			-- VARCHAR2(20 BYTE)
     MFL_DES_FIELDLABEL)				-- VARCHAR2(255 BYTE)
VALUES (569, 'Field 22', 38, 5, 'True', '\DESTINO:');







INSERT INTO MACRODEFINITION_MAC (
            MAC_NUM_ID,               	-- INTEGER
            ACC_NUM_ACCOUNTNUMBER,    	-- INTEGER
            MAC_NUM_MACRONUMBER,      	-- INTEGER
            MAC_NUM_MACROVERSION,     	-- INTEGER
            MAC_BOL_ISFORWARD,        	-- INTEGER
            MAC_BOL_AUTOPRINT,        	-- INTEGER
            MAC_NOM_MACRONAME,        	-- VARCHAR2(25 CHAR)
            MAC_DES_MACRODESCRIPTION, 	-- VARCHAR2(300 CHAR)
            MAC_DTM_CREATEDATE,       	-- DATE
            MAC_DTM_DEFINITIONDATE,   	-- DATE
            MAC_TXT_MACRODEFINITION,	-- VARCHAR2(3000 CHAR)
            MAC_NUM_DATATYPE,         	-- INTEGER
            MAC_NUM_MACROTYPE,        	-- INTEGER
            MAC_NUM_REPLYMACRO,       	-- INTEGER
            MAC_NUM_COLOR,            	-- INTEGER
            MAC_NUM_ICONID,           	-- INTEGER
            MAC_BOL_FORWARD)			-- INTEGER	
VALUES (570, 61643776, 17, 7, 0, 0, 'Macro_17', NULL, SYSDATE, SYSDATE, 
'----------SAIDA DE MAQUINISTA---------\\MATRICULA           _13308\TREM                       _13304\ESTACAO FINAL   _13302\\                                                  FUNCAO   DATA         HORA\INVERSAO                             _00203    _00808    _01105 \ENCERRAMENTO TREM   _00203    _00808    _01105      DE              PARA\PASSE                                    _00203    _00808    _01105      _13303    _13303\', 0, 2, 0, 0, 0, 0);

INSERT INTO MACROFIELDDEFINITION_MFL (
     MAC_NUM_ID,								-- INTEGER  
     MFL_NOM_FIELDNAME,         -- VARCHAR2(20 BYTE)
     MFL_NUM_FIELDTYPE,   			-- INTEGER
     MFL_NUM_FIELDLENGTH, 			-- INTEGER
     MFL_BOL_MUSTBEFILLED,			-- VARCHAR2(20 BYTE)
     MFL_DES_FIELDLABEL)				-- VARCHAR2(255 BYTE)
VALUES (570, 'Field 01', 38, 8, 'True', '\MATRICULA:');

INSERT INTO MACROFIELDDEFINITION_MFL (
     MAC_NUM_ID,								-- INTEGER  
     MFL_NOM_FIELDNAME,         -- VARCHAR2(20 BYTE)
     MFL_NUM_FIELDTYPE,   			-- INTEGER
     MFL_NUM_FIELDLENGTH, 			-- INTEGER
     MFL_BOL_MUSTBEFILLED,			-- VARCHAR2(20 BYTE)
     MFL_DES_FIELDLABEL)				-- VARCHAR2(255 BYTE)
VALUES (570, 'Field 02', 38, 8, 'True', '\TREM:');

INSERT INTO MACROFIELDDEFINITION_MFL (
     MAC_NUM_ID,								-- INTEGER  
     MFL_NOM_FIELDNAME,         -- VARCHAR2(20 BYTE)
     MFL_NUM_FIELDTYPE,   			-- INTEGER
     MFL_NUM_FIELDLENGTH, 			-- INTEGER
     MFL_BOL_MUSTBEFILLED,			-- VARCHAR2(20 BYTE)
     MFL_DES_FIELDLABEL)				-- VARCHAR2(255 BYTE)
VALUES (570, 'Field 03', 38, 8, 'True', '\ESTAÇÃO FINAL:');

INSERT INTO MACROFIELDDEFINITION_MFL (
     MAC_NUM_ID,								-- INTEGER  
     MFL_NOM_FIELDNAME,         -- VARCHAR2(20 BYTE)
     MFL_NUM_FIELDTYPE,   			-- INTEGER
     MFL_NUM_FIELDLENGTH, 			-- INTEGER
     MFL_BOL_MUSTBEFILLED,			-- VARCHAR2(20 BYTE)
     MFL_DES_FIELDLABEL)				-- VARCHAR2(255 BYTE)
VALUES (570, 'Field 04', 38, 5, 'True', '\FUNÇÃO_1:');

INSERT INTO MACROFIELDDEFINITION_MFL (
     MAC_NUM_ID,								-- INTEGER  
     MFL_NOM_FIELDNAME,         -- VARCHAR2(20 BYTE)
     MFL_NUM_FIELDTYPE,   			-- INTEGER
     MFL_NUM_FIELDLENGTH, 			-- INTEGER
     MFL_BOL_MUSTBEFILLED,			-- VARCHAR2(20 BYTE)
     MFL_DES_FIELDLABEL)				-- VARCHAR2(255 BYTE)
VALUES (570, 'Field 05', 38, 5, 'True', '\DATA_1:');

INSERT INTO MACROFIELDDEFINITION_MFL (
     MAC_NUM_ID,								-- INTEGER  
     MFL_NOM_FIELDNAME,         -- VARCHAR2(20 BYTE)
     MFL_NUM_FIELDTYPE,   			-- INTEGER
     MFL_NUM_FIELDLENGTH, 			-- INTEGER
     MFL_BOL_MUSTBEFILLED,			-- VARCHAR2(20 BYTE)
     MFL_DES_FIELDLABEL)				-- VARCHAR2(255 BYTE)
VALUES (570, 'Field 06', 38, 5, 'True', '\HORA_1:');

INSERT INTO MACROFIELDDEFINITION_MFL (
     MAC_NUM_ID,								-- INTEGER  
     MFL_NOM_FIELDNAME,         -- VARCHAR2(20 BYTE)
     MFL_NUM_FIELDTYPE,   			-- INTEGER
     MFL_NUM_FIELDLENGTH, 			-- INTEGER
     MFL_BOL_MUSTBEFILLED,			-- VARCHAR2(20 BYTE)
     MFL_DES_FIELDLABEL)				-- VARCHAR2(255 BYTE)
VALUES (570, 'Field 07', 38, 5, 'True', '\FUNÇÃO_2:');

INSERT INTO MACROFIELDDEFINITION_MFL (
     MAC_NUM_ID,								-- INTEGER  
     MFL_NOM_FIELDNAME,         -- VARCHAR2(20 BYTE)
     MFL_NUM_FIELDTYPE,   			-- INTEGER
     MFL_NUM_FIELDLENGTH, 			-- INTEGER
     MFL_BOL_MUSTBEFILLED,			-- VARCHAR2(20 BYTE)
     MFL_DES_FIELDLABEL)				-- VARCHAR2(255 BYTE)
VALUES (570, 'Field 08', 38, 5, 'True', '\DATA_2:');

INSERT INTO MACROFIELDDEFINITION_MFL (
     MAC_NUM_ID,								-- INTEGER  
     MFL_NOM_FIELDNAME,         -- VARCHAR2(20 BYTE)
     MFL_NUM_FIELDTYPE,   			-- INTEGER
     MFL_NUM_FIELDLENGTH, 			-- INTEGER
     MFL_BOL_MUSTBEFILLED,			-- VARCHAR2(20 BYTE)
     MFL_DES_FIELDLABEL)				-- VARCHAR2(255 BYTE)
VALUES (570, 'Field 09', 38, 5, 'True', '\HORA_2:');

INSERT INTO MACROFIELDDEFINITION_MFL (
     MAC_NUM_ID,								-- INTEGER  
     MFL_NOM_FIELDNAME,         -- VARCHAR2(20 BYTE)
     MFL_NUM_FIELDTYPE,   			-- INTEGER
     MFL_NUM_FIELDLENGTH, 			-- INTEGER
     MFL_BOL_MUSTBEFILLED,			-- VARCHAR2(20 BYTE)
     MFL_DES_FIELDLABEL)				-- VARCHAR2(255 BYTE)
VALUES (570, 'Field 10', 38, 5, 'True', '\FUNÇÃO_3:');

INSERT INTO MACROFIELDDEFINITION_MFL (
     MAC_NUM_ID,								-- INTEGER  
     MFL_NOM_FIELDNAME,         -- VARCHAR2(20 BYTE)
     MFL_NUM_FIELDTYPE,   			-- INTEGER
     MFL_NUM_FIELDLENGTH, 			-- INTEGER
     MFL_BOL_MUSTBEFILLED,			-- VARCHAR2(20 BYTE)
     MFL_DES_FIELDLABEL)				-- VARCHAR2(255 BYTE)
VALUES (570, 'Field 11', 38, 5, 'True', '\DATA_3:');

INSERT INTO MACROFIELDDEFINITION_MFL (
     MAC_NUM_ID,								-- INTEGER  
     MFL_NOM_FIELDNAME,         -- VARCHAR2(20 BYTE)
     MFL_NUM_FIELDTYPE,   			-- INTEGER
     MFL_NUM_FIELDLENGTH, 			-- INTEGER
     MFL_BOL_MUSTBEFILLED,			-- VARCHAR2(20 BYTE)
     MFL_DES_FIELDLABEL)				-- VARCHAR2(255 BYTE)
VALUES (570, 'Field 12', 38, 5, 'True', '\HORA_3:');

INSERT INTO MACROFIELDDEFINITION_MFL (
     MAC_NUM_ID,								-- INTEGER  
     MFL_NOM_FIELDNAME,         -- VARCHAR2(20 BYTE)
     MFL_NUM_FIELDTYPE,   			-- INTEGER
     MFL_NUM_FIELDLENGTH, 			-- INTEGER
     MFL_BOL_MUSTBEFILLED,			-- VARCHAR2(20 BYTE)
     MFL_DES_FIELDLABEL)				-- VARCHAR2(255 BYTE)
VALUES (570, 'Field 13', 38, 5, 'True', '\DE:');

INSERT INTO MACROFIELDDEFINITION_MFL (
     MAC_NUM_ID,								-- INTEGER  
     MFL_NOM_FIELDNAME,         -- VARCHAR2(20 BYTE)
     MFL_NUM_FIELDTYPE,   			-- INTEGER
     MFL_NUM_FIELDLENGTH, 			-- INTEGER
     MFL_BOL_MUSTBEFILLED,			-- VARCHAR2(20 BYTE)
     MFL_DES_FIELDLABEL)				-- VARCHAR2(255 BYTE)
VALUES (570, 'Field 14', 38, 5, 'True', '\PARA:');