--drop table ROTAS_PRODUCAO;
--drop sequence ACTWEB.ROTAS_PRODUCAO_ID;

CREATE TABLE ROTAS_PRODUCAO (    
  ROT_ID_ROT         NUMBER             NOT NULL PRIMARY KEY,
  ROT_NOM_COR        VARCHAR(255 BYTE)  NOT NULL,
  ROT_NOM_ROT        VARCHAR(255 BYTE)  NOT NULL,
  ROT_PRF_TRM        VARCHAR(255 BYTE)  NOT NULL,
  ROT_DTE_PUB        DATE               NOT NULL,
  ROT_ATV_SN         VARCHAR2(1 BYTE)   NOT NULL);  
 
CREATE SEQUENCE ACTWEB.ROTAS_PRODUCAO_ID
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
INSERT INTO ROTAS_PRODUCAO (ROT_ID_ROT, ROT_NOM_COR, ROT_NOM_ROT, ROT_PRF_TRM, ROT_DTE_PUB, ROT_ATV_SN) VALUES (1, 'Cento Leste', 'EEL-EBJ', 'J, C', SYSDATE, 'S'); 
INSERT INTO ROTAS_PRODUCAO (ROT_ID_ROT, ROT_NOM_COR, ROT_NOM_ROT, ROT_PRF_TRM, ROT_DTE_PUB, ROT_ATV_SN) VALUES (2, 'Centro Leste', 'RAMAL BH', 'J, C, M, D', SYSDATE, 'S');
INSERT INTO ROTAS_PRODUCAO (ROT_ID_ROT, ROT_NOM_COR, ROT_NOM_ROT, ROT_PRF_TRM, ROT_DTE_PUB, ROT_ATV_SN) VALUES (3, 'Minas Rio', 'EAO-EBM', 'C', SYSDATE, 'S');
INSERT INTO ROTAS_PRODUCAO (ROT_ID_ROT, ROT_NOM_COR, ROT_NOM_ROT, ROT_PRF_TRM, ROT_DTE_PUB, ROT_ATV_SN) VALUES (4, 'Centro Sudeste', 'EAU-ZRP', 'J, C, M, D, X, E', SYSDATE, 'S');
INSERT INTO ROTAS_PRODUCAO (ROT_ID_ROT, ROT_NOM_COR, ROT_NOM_ROT, ROT_PRF_TRM, ROT_DTE_PUB, ROT_ATV_SN) VALUES (5, 'Centro Sudeste', 'ZRP-ZOP', 'J, C, M, D, X, E', SYSDATE, 'S');
INSERT INTO ROTAS_PRODUCAO (ROT_ID_ROT, ROT_NOM_COR, ROT_NOM_ROT, ROT_PRF_TRM, ROT_DTE_PUB, ROT_ATV_SN) VALUES (6, 'Baixada', 'ZBL-ZPG', 'J, C, M', SYSDATE, 'S');
INSERT INTO ROTAS_PRODUCAO (ROT_ID_ROT, ROT_NOM_COR, ROT_NOM_ROT, ROT_PRF_TRM, ROT_DTE_PUB, ROT_ATV_SN) VALUES (7, 'Baixada', 'MARGEM ESQUERDA', 'J, C', SYSDATE, 'S');
INSERT INTO ROTAS_PRODUCAO (ROT_ID_ROT, ROT_NOM_COR, ROT_NOM_ROT, ROT_PRF_TRM, ROT_DTE_PUB, ROT_ATV_SN) VALUES (8, 'Baixada', 'MARGEM DIREITA', 'J, C', SYSDATE, 'S');

SELECT * FROM ROTAS_PRODUCAO;