drop table ACTWEB.MOTIVO_PARADA;
drop sequence ACTWEB.MOTIVO_PARADA_ID;

CREATE TABLE ACTWEB.MOTIVO_PARADA (    
  MOT_ID_MOT         NUMBER, 
  GRU_ID_GRU         NUMBER, 
  MOT_AUTO_TRAC      NUMBER, 
  MOT_NOME           VARCHAR2(050 BYTE), 
  MOT_APLICACAO      VARCHAR2(500 BYTE), 
  MOT_ATIVO          VARCHAR2(001 BYTE));

ALTER TABLE ACTWEB.MOTIVO_PARADA ADD ( CONSTRAINT PK_MOTIVO_PARAD PRIMARY KEY (MOT_ID_MOT));

CREATE SEQUENCE ACTWEB.MOTIVO_PARADA_ID
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 1, 1, 'ACIDENTE', 'APLICA-SE A TODO TREM QUE PAROU DEVIDO ACIDENTE.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 2, 2, 'PREFERÊNCIA OUTRO TREM', 'APLICA-SE A TODO TREM CUJA PARADA SEJA EM FUNÇÃO DO CCO TER CONCEDIDO PASSAGEM A OUTRO TREM.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 2, 3, 'AGUARDANDO LICENÇA', 'APLICA-SE A TODO TREM EM CONDIÇÕES DE CIRCULAÇÃO QUE ESTEJAM AGUARDANDO LICENÇA (CONSIDERANDO QUE TODOS OS SISTEMAS DE LICENCIAMENTO ESTEJAM EM FUNCIONAMENTO).', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 2, 4, 'CRUZAMENTO', 'APLICA-SE A TODO TREM AGUARDANDO OUTRO TREM EM SENTIDO CONTRÁRIO.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 2, 5, 'TREM A FRENTE', 'APLICA-SE A TODO TREM QUE NÃO POSSA CIRCULAR, DEVIDO UM TREM NO MESMO SENTIDO NÃO TER ATINGIDO A PRÓXIMA SB OU ESTAÇÃO. CTF DEVE VERIFICAR CAPACIDADE DO PÁTIO À FRENTE, PARA CONFIRMAR A APROPRIAÇÃO DO CÓDIGO.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 2, 6, 'AGUARDANDO HELPER', 'APLICA-SE A TODO TREM PARADO EM LOCAL DIMENSIONADO PELO PLANO DE TRENS, PARA RECEBIMENTO DE TRAÇÃO EXTRA DENOMINADA HELPER.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 2, 7, 'AGUARDANDO COMPLEMENTO DE TRAÇÃO', 'APLICA-SE A TODO TREM PARADO EM LOCAL DIMENSIONADO PELO PLANO DE TRENS, PARA RECEBIMENTO DE TRAÇÃO.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 2, 8, 'PARALIZAÇÃO SISTEMA LICENCIAMENTO', 'APLICA-SE A TODO TREM PARADO DEVIDO PARALIZAÇÃO DO SISTEMA DE LICENCIAMENTO.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 2, 9, 'AGUARDANDO OUTRA FERROVIA', 'APLICA-SE A TODO TREM PARADO, PROGRAMADO EM FILA DE INTERCÂMBIO, QUE ESTÁ AGUARDANDO RECEBIMENTO POR OUTRA FERROVIA.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 3, 13, 'AVARIA DE EQUIPAMENTO DE ELETROELETRÔNICA', 'APLICA-SE A TODO TREM PARADO DEVIDO AVARIA NOS EQUIPAMENTOS DE ELETRO, SISTEMAS DE SINALIZAÇÃO, AVARIA DE SEMÁFORO, DETECTOR DE DESCARRILAMENTO, CHAVE TELECOMANDADA, HOUSE, DETECTOR DE CAUDA (DCA, EOT, ATX, ETC.), FALTA DE ENERGIA DA CONCESSIONÁRIA.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 3, 14, 'FAIXA DE MANUTENÇÃO DE ELETROELETRÔNICA', 'APLICA-SE A TODO TREM PARADO DEVIDO FAIXA DE MANUTENÇÃO DE ELETROELETRÔNICA PROGRAMADA.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 3, 15, 'AVARIA DE EQUIPAMENTO DE BORDO', 'APLICA-SE A TODO TREM PARADO DEVIDO AVARIA DE EQUIPAMENTO DE BORDO.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 3, 16, 'AVARIA EQUIPAMENTO DE BORDO DE OUTRO TREM', 'APLICA-SE A TODO TREM PARADO DEVIDO AVARIA DE EQUIPAMENTO DE BORDO DE OUTRO TREM. ', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 4, 20, 'AVARIA DE LOCOMOTIVA ', 'APLICA-SE A TODO TREM PARADO DEVIDO AVARIA DE LOCOMOTIVA.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 4, 21, 'AVARIA DE LOCOMOTIVA DE OUTRO TREM', 'APLICA-SE A TODO TREM PARADO DEVIDO AVARIA DE LOCOMOTIVA DE OUTRO TREM.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 5, 24, 'OBRAS DE INFRAESTRUTURA', 'APLICA-SE A TODO TREM PARADO DEVIDO OBRAS DE INFRAESTRUTURA (EXCETO OBRAS NA VIA PERMANENTE), OBRAS DE AMPLIAÇÃO DE PÁTIOS, ETC.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 6, 25, 'TROCA DE EQUIPE', 'APLICA-SE A TODO TREM PARADO DEVIDO TROCA DE EQUIPE.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 6, 26, 'REVISTA DE COMPOSIÇÃO', 'APLICA-SE A TODO TREM PARADO DEVIDO REVISTA DE COMPOSIÇÃO, NO QUAL AINDA NÃO SE SABE O REAL MOTIVO DA PARADA. APLICA-SE TAMBÉM PARA O TREM QUE PARAR SOMENTE PARA TESTE DE TREM.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 6, 27, 'FALTA DE EQUIPE', 'APLICA-SE A TODO TREM PARADO DEVIDO FALTA DE EQUIPE.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 6, 28, 'EMERGÊNCIA DO TREM', 'APLICA-SE A TODO TREM PARADO DEVIDO EMERGÊNCIA DO TREM.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 6, 29, 'FALHA DE OPERAÇÃO', 'APLICA-SE A TODO TREM QUE PAROU DEVIDO FALHA OPERACIONAL, CONSTATADO APÓS O EVENTO DA PARADA, DEVE SER APROPRIADO SOMENTE APÓS O ENVIO DO PLEITO APROVADO PARA O CCO.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 6, 30, 'NÃO VENCE RAMPA', 'APLICA-SE A TODO TREM PARADO EM RAMPA, QUANDO O MAQUINISTA NÃO INDENTIFICA NENHUMA AVARIA NA LOCOMOTIVA OU PROBLEMA DE FREIO APLICADO E POR ALGUM MOTIVO NÃO CONSEGUE VENCER RAMPA.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 6, 31, 'FALTA DE INSUMO', 'APLICA-SE A TODO TREM PARADO DEVIDO FALTA DE INSUMO (ÁGUA, ÓLEO COMBUSTÍVEL, ÓLEO, AREIA, ETC).', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 6, 32, 'NECESSIDADE FISIOLÓGICA', 'APLICA-SE A TODO TREM PARADO DEVIDO NECESSIDADE FISIOLÓGICA.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 6, 33, 'AÇÃO DE TERCEIROS', 'APLICA-SE A TODO TREM PARADO DEVIDO AÇÃO DE TERCEIROS.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 6, 34, 'ECONOMIA DE COMBUSTÍVEL', 'APLICA-SE A TODO TREM PARADO PARA LIGAR/DESLIGAR LOCOMOTIVA NO TRECHO, PARA MELHOR UTILIZAÇÃO DA CAPACIDADE DE TRAÇÃO E REDUÇÃO DE CONSUMO DE COMBUSTÍVEL.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 6, 35, 'MANIPULAÇÃO DE AMV', 'APLICA-SE A TODO TREM PARADO DEVIDO MANIPULAÇÃO DE AMV, ENTRADA E SAÍDA DE PÁTIO, INVERSÃO DE ROTA, EVENTOS REFERENTES A CHAVE DE MOLA, ETC.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 7, 37, 'MANOBRA', 'APLICA-SE A TODO TREM PARADO DEVIDO MANOBRA NO PÁTIO DA ESTAÇÃO, PARA ANEXAR OU DESANEXAR VEÍCULOS DO TREM. POSICIONAMENTO DE VEÍCULOS NO PÁTIO, TERMINAL, OFICINA, POSTOS E TESTE DO TREM.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 7, 38, 'PÁTIO CONGESTIONADO', 'APLICA-SE A TODO TREM PARADO DEVIDO O PÁTIO QUE O TREM IRÁ PASSAR, ENCERRAR OU MANOBRAR ESTAR CONGESTIONADO, OU SEJA, TODAS AS LINHAS DE ACESSO ESTAREM OBSTRUÍDAS POR VEÍCULOS.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 7, 39, 'ABASTECIMENTO', 'APLICA-SE A TODO TREM PARADO DEVIDO ABASTECIMENTO.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 7, 40, 'CARGA IRREGULAR', 'APLICA-SE A TODO TREM PARADO DEVIDO CARGA IRREGULAR.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 7, 41, 'ABASTECIMENTO DE TREM À FRENTE', 'APLICA-SE A TODO TREM PARADO DEVIDO ABASTECIMENTO DE TREM À FRENTE.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 7, 42, 'MANOBRA DE TREM À FRENTE', 'APLICA-SE A TODO TREM PARADO DEVIDO MANOBRA DE TREM À FRENTE.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 8, 46, 'AGUARDANDO TERMINAL/PORTO', 'APLICA-SE A TODO TREM PARADO DEVIDO AGUARDAR TERMINAL/PORTO. DESDE QUE, NÃO ESTEJA PROGRAMADO EM FILA DE INTERCÂMBIO (FILA PARA CARREGAMENTO/DESCARGA).', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 9, 50, 'AVARIA DE VAGÃO', 'APLICA-SE A TODO TREM PARADO DEVIDO AVARIA DE VAGÃO.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 9, 51, 'AVARIA DE VAGÃO DE OUTRO TREM', 'APLICA-SE A TODO TREM PARADO DEVIDO AVARIA DE VAGÃO DE OUTRO TREM.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 9, 52, 'FAST TRACK', 'APLICA-SE A TODO TREM PARADO PARA REALIZAÇÃO DO FAST TRACK.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 10, 55, 'PRO CARGA PERIGOSA', 'APLICA-SE A TODO TREM PARADO DEVIDO PRO DE CARGA PERIGOSA.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 10, 56, 'AVARIA DE EQUIPAMENTO DE VP', 'APLICA-SE A TODO TREM PARADO DEVIDO AVARIA DE DE EQUIPAMENTO DE VIA PERMANENTE.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 10, 57, 'FAIXA MANUTENÇÃO VP PROGRAMADA', 'APLICA-SE A TODO TREM PARADO DEVIDO FAIXA DE MANUTENÇÃO DE VIA PERMANENTE PROGRAMADA.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 10, 58, 'FAIXA MANUTENÇÃO VP CORRETIVA', 'APLICA-SE A TODO TREM PARADO DEVIDO FAIXA DE MANUTENÇÃO DE VIA PERMANENTE NÃO PROGRAMADA, EVENTOS DE RONDA, ETC.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 10, 59, 'PRO TEMPERATURA', 'APLICA-SE A TODO TREM PARADO DEVIDO PRO DE TEMPERATURA.', 'S');
INSERT INTO MOTIVO_PARADA (MOT_ID_MOT, GRU_ID_GRU, MOT_AUTO_TRAC, MOT_NOME, MOT_APLICACAO, MOT_ATIVO) VALUES (MOTIVO_PARADA_ID.NEXTVAL, 10, 60, 'FENÔMENO DA NATUREZA', 'APLICA-SE A TODO TREM PARADO DEVIDO FENÔMENO DA NATUREZA.', 'S');
