
drop table ACTWEB.ABREVIAR;
drop sequence ACTWEB.ABREVIAR_ID;

CREATE TABLE ACTWEB.ABREVIAR (	
  ABV_ID_ABV         NUMBER, 
  ABV_EXTENSO        VARCHAR2(30 BYTE), 
  ABV_ABREVIADO      VARCHAR2(30 BYTE),
  ABV_ATIVO_SN       VARCHAR2(1 BYTE));

ALTER TABLE ACTWEB.ABREVIAR ADD ( CONSTRAINT PK_ABREVIAR PRIMARY KEY (ABV_ID_ABV) );

CREATE INDEX ACTWEB.ABV_EXTENSO on ACTWEB.ABREVIAR('ABV_EXTENSO');

CREATE SEQUENCE ACTWEB.ABREVIAR_ID
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  