--Cria tablespace

CREATE TABLESPACE ACTWEB DATAFILE 
  'D:\Oracle\product\11.2.0\dbhome_1\oradata\actweb' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE 10240M
LOGGING
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT MANUAL
FLASHBACK ON;



-- Cria usuario Actweb na tablespace actweb com permissoes necessarias

CREATE USER ACTWEB
  IDENTIFIED BY VALUES '1A902C72F31B9ED7'
  DEFAULT TABLESPACE ACTWEB
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for ACTWEB 
  GRANT CONNECT TO ACTWEB;
  GRANT RESOURCE TO ACTWEB;
  ALTER USER ACTWEB DEFAULT ROLE ALL;
  -- 10 System Privileges for ACTWEB 
  GRANT CREATE INDEXTYPE TO ACTWEB;
  GRANT UNLIMITED TABLESPACE TO ACTWEB;
  GRANT CREATE SEQUENCE TO ACTWEB;
  GRANT CREATE VIEW TO ACTWEB;
  GRANT CREATE TRIGGER TO ACTWEB;
  GRANT CREATE TYPE TO ACTWEB;
  GRANT CREATE PROCEDURE TO ACTWEB;
  GRANT CREATE JOB TO ACTWEB;
  GRANT CREATE TABLE TO ACTWEB;
  GRANT CREATE USER TO ACTWEB;
  GRANT CREATE SESSION TO ACTWEB;
  GRANT READ, WRITE ON DIRECTORY DATA_PUMP_DIR TO ACTWEB;
  GRANT SELECT_CATALOG_ROLE TO ACTWEB;
  GRANT SELECT ANY DICTIONARY TO ACTWEB;  
  GRANT ADVISOR TO ACTWEB;
  GRANT ADMINISTER SQL TUNING SET TO ACTWEB; 
  -- 9 Tablespace Quotas for ACTWEB 
  ALTER USER ACTWEB QUOTA UNLIMITED ON ACTTRPI;
  ALTER USER ACTWEB QUOTA UNLIMITED ON ACTTRGD;
  ALTER USER ACTWEB QUOTA UNLIMITED ON ACTTRPD;
  ALTER USER ACTWEB QUOTA UNLIMITED ON ACTCADD;
  ALTER USER ACTWEB QUOTA UNLIMITED ON ACTHSTD;
  ALTER USER ACTWEB QUOTA UNLIMITED ON ACTCADI;
  ALTER USER ACTWEB QUOTA UNLIMITED ON ACTHSTI;
  ALTER USER ACTWEB QUOTA UNLIMITED ON ACTWEB;
  ALTER USER ACTWEB QUOTA UNLIMITED ON ACTTRGI;
  ALTER USER ACTWEB IDENTIFIED BY engesis;
  
  -- criando a tabela usuarios 
  


