insert into nivel_acesso(id,nome) values (1,'PAINEL'); 									
insert into nivel_acesso(id,nome) values (2,'APOIO'); 								
insert into nivel_acesso(id,nome) values (3,'CAT'); 								
insert into nivel_acesso(id,nome) values (4,'CTD'); 									
insert into nivel_acesso(id,nome) values (5,'GERENTE'); 									
insert into nivel_acesso(id,nome) values (6,'HELP DESK'); 									
insert into nivel_acesso(id,nome) values (7,'MACRO 50'); 									
insert into nivel_acesso(id,nome) values (8,'CCE EMERGENCIA'); 									
insert into nivel_acesso(id,nome) values (9,'OP ELET'); 								
insert into nivel_acesso(id,nome) values (10,'UNILOG'); 								
insert into nivel_acesso(id,nome) values (11,'OP VP'); 								
insert into nivel_acesso(id,nome) values (12,'PAINEL'); 								
insert into nivel_acesso(id,nome) values (13,'PCM'); 						
insert into nivel_acesso(id,nome) values (14,'PCM_ELETRO'); 							
insert into nivel_acesso(id,nome) values (15,'SUPERVISOR');							
insert into nivel_acesso(id,nome) values (16,'TECNICO');							
insert into nivel_acesso(id,nome) values (17,'TELECOM');							
insert into nivel_acesso(id,nome) values (18,'ADMINISTRADOR');								
insert into nivel_acesso(id,nome) values (19,'VP ADM');
insert into nivel_acesso(id,nome) values (20,'OPERADORFNS');